// Integrity checks for the tournament-meta artifact (data/pro_meta.json,
// generated by `npm run prometa` from the pro corpus and served by /api/meta/pro).
import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { HERO_IDS } from '../../shared/interactions';

const FILE = path.resolve(process.cwd(), 'data', 'pro_meta.json');

test('pro_meta.json exists, parses, and has a sane window', () => {
  assert.ok(fs.existsSync(FILE), 'pro_meta.json missing — run `npm run prometa`');
  const meta = JSON.parse(fs.readFileSync(FILE, 'utf-8'));
  assert.ok(meta.matches >= 100, `window too thin: ${meta.matches} matches`);
  assert.ok(meta.leagues >= 2, 'expected multiple leagues in the window');
  assert.ok(Object.keys(meta.heroes).length >= 80, 'expected broad hero coverage');
});

test('pro meta rates are within range and internally consistent', () => {
  const meta = JSON.parse(fs.readFileSync(FILE, 'utf-8'));
  const validIds = new Set(Object.values(HERO_IDS));
  for (const [idStr, h] of Object.entries<Record<string, number>>(meta.heroes)) {
    const id = Number(idStr);
    // Hero ids come straight from OpenDota; every one the engine knows must be valid,
    // but brand-new heroes may not be in HERO_IDS yet — only check known ones strictly.
    if (validIds.has(id)) {
      for (const k of ['pickRate', 'banRate', 'contestRate', 'winRate'] as const) {
        assert.ok(h[k] >= 0 && h[k] <= 1, `hero ${id}: ${k} out of range (${h[k]})`);
      }
      assert.ok(h.picks >= h.wins, `hero ${id}: more wins than picks`);
    }
  }
});
