import type { Hero, MetaRole, Role, UtilityTag } from './types';

// Full metadata keyed by OpenDota hero short name (npc_dota_hero_X → X)
// This covers all 124 heroes. Detailed entries override defaults derived from OpenDota roles.
export const HERO_METADATA: Record<string, Partial<Hero>> = {
  antimage: {
    preferredRoles: ['carry'],
    strengths: ['Exceptional mana burn', 'High mobility with Blink', 'Hard to catch', 'Snowballs vs magic lineups'],
    weaknesses: ['Weak early game', 'Falls behind without farm', 'Weak vs physical damage'],
    powerSpikes: ['Level 6 (Mana Void)', 'BF + Manta', 'Level 25'],
    utilityTags: ['mobility', 'scaling', 'burst'],
    needs: ['farm protection', 'early support', 'space creation'],
  },
  axe: {
    preferredRoles: ['offlane'],
    strengths: ['Strong lane presence', 'Reliable kill potential', 'Good vs illusions'],
    weaknesses: ['Slow', 'No ranged harass', 'Falls off late'],
    powerSpikes: ['Level 6 (Culling Blade)', 'Blink Dagger', 'Blade Mail'],
    utilityTags: ['initiation', 'lockdown', 'lane_pressure'],
    needs: ['follow-up damage', 'ranged support', 'late-game carries'],
  },
  bane: {
    preferredRoles: ['hard_support'],
    strengths: ['Strong disables', 'Reliable Nightmare', 'Fiend\'s Grip lockdown'],
    weaknesses: ['No burst', 'Squishy', 'Falls off without items'],
    powerSpikes: ['Level 6 (Fiend\'s Grip)', 'Aether Lens', 'Aghanim\'s Scepter'],
    utilityTags: ['lockdown', 'silence', 'stun'],
    needs: ['physical damage dealers', 'heroes to follow up on disables'],
  },
  bloodseeker: {
    preferredRoles: ['carry', 'offlane'],
    strengths: ['Strong ganking', 'Vision on low-HP enemies', 'Good lane harass'],
    weaknesses: ['Falls off very late', 'Countered by BKB', 'Position dependent'],
    powerSpikes: ['Level 6 (Rupture)', 'Blade Mail', 'Level 12'],
    utilityTags: ['lane_pressure', 'burst', 'vision'],
    needs: ['reliable stuns', 'teamfight follow-up'],
  },
  crystal_maiden: {
    preferredRoles: ['hard_support'],
    strengths: ['Global mana aura', 'Strong lane harass', 'Reliable Frostbite', 'High teamfight damage'],
    weaknesses: ['Very slow', 'Squishy', 'Easy kill in teamfights'],
    powerSpikes: ['Level 6 (Freezing Field)', 'Aether Lens', 'Blink Dagger'],
    utilityTags: ['stun', 'aura_carrier', 'wave_clear', 'lockdown'],
    needs: ['peel', 'BKB cover', 'positioning support'],
  },
  drow_ranger: {
    preferredRoles: ['carry'],
    strengths: ['High single-target damage', 'Global aura for ranged team', 'Scales well'],
    weaknesses: ['No mobility', 'Countered by gap-closers', 'Weak vs melee initiators'],
    powerSpikes: ['Level 6 (Marksmanship)', 'Dragon Lance', 'Aghanim\'s Scepter'],
    utilityTags: ['lane_pressure', 'aura_carrier', 'scaling'],
    needs: ['front-line', 'space makers', 'ranged team composition'],
  },
  earthshaker: {
    preferredRoles: ['support'],
    strengths: ['Massive AoE teamfight', 'Reliable stun', 'Great with illusion lineups'],
    weaknesses: ['Blink-dependent', 'Hard to play', 'Minimal damage without items'],
    powerSpikes: ['Blink Dagger', 'Level 6 (Echo Slam)', 'Aghanim\'s Scepter'],
    utilityTags: ['stun', 'initiation', 'lockdown', 'wave_clear'],
    needs: ['high-damage follows', 'illusion or summon enemies'],
  },
  juggernaut: {
    preferredRoles: ['carry'],
    strengths: ['Blade Fury magic immunity', 'Healing Ward sustain', 'Strong laner', 'Scales'],
    weaknesses: ['Short attack range', 'Falls off vs heavy disables', 'Predictable'],
    powerSpikes: ['Level 6 (Omnislash)', 'Battle Fury', 'Aghanim\'s Scepter'],
    utilityTags: ['burst', 'heal', 'mobility', 'scaling'],
    needs: ['lane support', 'front-line', 'peel'],
  },
  mirana: {
    preferredRoles: ['support', 'mid'],
    strengths: ['Long-range stun', 'Global ultimate', 'Good escape', 'Versatile'],
    weaknesses: ['Skill-shot dependent', 'No reliable disable without arrow hit'],
    powerSpikes: ['Level 6 (Moonlight Shadow)', 'Aghanim\'s Scepter', 'Level 12'],
    utilityTags: ['stun', 'mobility', 'save', 'vision'],
    needs: ['reliable follow-up', 'backup disable'],
  },
  morphling: {
    preferredRoles: ['carry'],
    strengths: ['Extremely hard to kill', 'High burst damage', 'Adaptive attribute shift'],
    weaknesses: ['Weak early laning', 'Mechanically demanding', 'Mana-hungry'],
    powerSpikes: ['Level 6', 'Ethereal Blade', 'Full items'],
    utilityTags: ['burst', 'mobility', 'scaling'],
    needs: ['early protection', 'space creation'],
  },
  nevermore: {
    preferredRoles: ['mid'],
    strengths: ['Massive burst damage', 'Strong mid-game spike', 'Presence of the Dark Lord aura'],
    weaknesses: ['Falls off very late', 'Squishy', 'No reliable escape'],
    powerSpikes: ['Level 6 (Requiem)', 'Shadow Blade / Eul\'s', 'Level 16'],
    utilityTags: ['burst', 'aura_carrier', 'wave_clear', 'lane_pressure'],
    needs: ['peel', 'setup', 'early-game supports'],
  },
  phantom_lancer: {
    preferredRoles: ['carry'],
    strengths: ['Overwhelms single-target teams', 'Hard to focus', 'Scales massively'],
    weaknesses: ['Hard countered by AoE', 'Weak early game'],
    powerSpikes: ['Diffusal Blade + Manta', 'Level 6', 'Full illusion build'],
    utilityTags: ['scaling', 'mobility'],
    needs: ['AoE protection', 'early support', 'time to farm'],
  },
  puck: {
    preferredRoles: ['mid'],
    strengths: ['Strong initiation', 'High mobility', 'Silence and lockdown', 'Slippery'],
    weaknesses: ['Fragile', 'Falls off late if behind', 'Item-dependent'],
    powerSpikes: ['Blink Dagger', 'Level 6 (Dream Coil)', 'Aghanim\'s Scepter'],
    utilityTags: ['initiation', 'silence', 'lockdown', 'mobility'],
    needs: ['follow-up damage', 'BKB-piercing damage'],
  },
  pudge: {
    preferredRoles: ['support'],
    strengths: ['High kill threat', 'Dismember lockdown', 'Grows with kills'],
    weaknesses: ['Skill-shot reliant', 'Slow', 'Countered by mobile heroes'],
    powerSpikes: ['Level 6 (Dismember)', 'Aether Lens', 'Aghanim\'s Scepter'],
    utilityTags: ['lockdown', 'initiation', 'burst'],
    needs: ['follow-up damage', 'ranged setup', 'vision'],
  },
  razor: {
    preferredRoles: ['mid'],
    strengths: ['Strong laner', 'Steals damage from carries', 'Good vs right-click'],
    weaknesses: ['No mobility', 'Falls off vs magic damage', 'Needs levels'],
    powerSpikes: ['Level 6', 'Blade Mail', 'Eye of Skadi'],
    utilityTags: ['lane_pressure', 'tower_damage', 'aura_carrier'],
    needs: ['save support', 'teamfight follow-up'],
  },
  sand_king: {
    preferredRoles: ['offlane'],
    strengths: ['Massive teamfight AoE', 'Strong ganker', 'Good lane presence'],
    weaknesses: ['Blink-dependent', 'High skill floor', 'Channeled ultimate'],
    powerSpikes: ['Blink Dagger', 'Level 6 (Epicenter)', 'Aghanim\'s Scepter'],
    utilityTags: ['initiation', 'stun', 'wave_clear', 'lockdown'],
    needs: ['front-line', 'high-damage follow-up', 'BKB cover'],
  },
  storm_spirit: {
    preferredRoles: ['mid'],
    strengths: ['Extremely mobile', 'Strong snowball potential', 'Hard to catch'],
    weaknesses: ['Mana-hungry early', 'Falls off without farm', 'Countered by mana burn'],
    powerSpikes: ['Level 6 (Ball Lightning)', 'Bloodstone', 'Level 18+'],
    utilityTags: ['mobility', 'burst', 'lockdown', 'scaling'],
    needs: ['early lane support', 'room to snowball'],
  },
  sven: {
    preferredRoles: ['carry'],
    strengths: ['Massive teamfight damage', 'AoE stun', 'Tanky', 'Good with aura carriers'],
    weaknesses: ['No mobility', 'Slow attack speed normally', 'Easy to kite'],
    powerSpikes: ['Level 6 (God\'s Strength)', 'Echo Sabre', 'BKB + Daedalus'],
    utilityTags: ['stun', 'tower_damage', 'roshan', 'scaling', 'aura_carrier'],
    needs: ['aura carriers', 'setup from supports', 'blink-like initiation'],
  },
  tiny: {
    preferredRoles: ['mid', 'support'],
    strengths: ['Massive burst damage', 'High mobility (Aghs)', 'Strong ganks', 'Tower damage'],
    weaknesses: ['Falls off without items', 'Slow attack speed early'],
    powerSpikes: ['Level 3 combo', 'Aghanim\'s Scepter', 'Level 6'],
    utilityTags: ['burst', 'stun', 'initiation', 'tower_damage', 'roshan'],
    needs: ['follow-up lockdown', 'damage items'],
  },
  vengefulspirit: {
    preferredRoles: ['support'],
    strengths: ['Reliable stun', 'Damage reduction aura', 'Swap utility', 'Good lane harass'],
    weaknesses: ['Squishy', 'Swap can misfire', 'No escape'],
    powerSpikes: ['Level 6 (Nether Swap)', 'Aether Lens', 'Aghanim\'s Scepter'],
    utilityTags: ['stun', 'aura_carrier', 'initiation', 'save'],
    needs: ['follow-up damage', 'tank front-line'],
  },
  windrunner: {
    preferredRoles: ['support', 'mid'],
    strengths: ['High single-target damage', 'Shackle shot setup', 'Windrun escape'],
    weaknesses: ['Somewhat item-dependent', 'Falls off vs AoE'],
    powerSpikes: ['Level 6 (Focus Fire)', 'Aghanim\'s Shard', 'Maelstrom'],
    utilityTags: ['stun', 'burst', 'mobility', 'lane_pressure'],
    needs: ['team follow-up', 'AoE support'],
  },
  zuus: {
    preferredRoles: ['mid'],
    strengths: ['Global ultimate', 'Constant true sight', 'Huge teamfight damage'],
    weaknesses: ['No mobility', 'Squishy', 'Predictable'],
    powerSpikes: ['Level 6 (Thundergod\'s Wrath)', 'Aghanim\'s Scepter', 'Octarine Core'],
    utilityTags: ['burst', 'vision', 'wave_clear', 'tower_damage'],
    needs: ['save support', 'front-line', 'initiation'],
  },
  kunkka: {
    preferredRoles: ['mid'],
    strengths: ['Massive AoE damage', 'Strong initiation', 'Good aura carrier'],
    weaknesses: ['Skill-shot reliant', 'Needs farm', 'No escape'],
    powerSpikes: ['Level 6 (Ghostship)', 'Daedalus / BKB', 'Aghanim\'s Scepter'],
    utilityTags: ['stun', 'burst', 'initiation', 'wave_clear', 'aura_carrier'],
    needs: ['follow-up AoE', 'save support'],
  },
  lina: {
    preferredRoles: ['mid', 'support'],
    strengths: ['High burst damage', 'Reliable stun', 'Scales into carry', 'Good laner'],
    weaknesses: ['Squishy', 'Long cooldowns early', 'No mobility'],
    powerSpikes: ['Level 6 (Laguna Blade)', 'Aghanim\'s Scepter', 'Dragon Lance'],
    utilityTags: ['burst', 'stun', 'tower_damage', 'lane_pressure'],
    needs: ['peel', 'front-line', 'initiation'],
  },
  lion: {
    preferredRoles: ['hard_support'],
    strengths: ['Double disable', 'High burst damage', 'Reliable stun + hex', 'Mana drain'],
    weaknesses: ['Squishy', 'No mobility', 'Long cooldowns'],
    powerSpikes: ['Level 6 (Finger of Death)', 'Aether Lens', 'Aghanim\'s Scepter'],
    utilityTags: ['stun', 'lockdown', 'burst', 'silence'],
    needs: ['physical damage follow-up', 'front-line'],
  },
  witch_doctor: {
    preferredRoles: ['support', 'hard_support'],
    strengths: ['Strong healer', 'Paralyzing Cask chain stun', 'Massive Death Ward'],
    weaknesses: ['Channeled ultimate', 'Squishy', 'Needs protection'],
    powerSpikes: ['Level 6 (Death Ward)', 'Aghanim\'s Scepter', 'Aghanim\'s Shard'],
    utilityTags: ['stun', 'heal', 'burst', 'lockdown'],
    needs: ['BKB cover', 'peel', 'initiation'],
  },
  ancient_apparition: {
    preferredRoles: ['hard_support'],
    strengths: ['Counters healing lineups', 'Global ultimate', 'Good lane harass'],
    weaknesses: ['Skill-shot reliant', 'Low base damage', 'Squishy'],
    powerSpikes: ['Level 6 (Ice Blast)', 'Aether Lens', 'Aghanim\'s Scepter'],
    utilityTags: ['burst', 'lockdown', 'vision', 'wave_clear'],
    needs: ['physical damage dealers', 'initiation', 'front-line'],
  },
  invoker: {
    preferredRoles: ['mid'],
    strengths: ['Highest skill ceiling', 'Extremely versatile', 'Scales to late game'],
    weaknesses: ['Requires high skill', 'Weak very early', 'Punished by disjoints'],
    powerSpikes: ['Level 6+', 'Aghanim\'s Scepter', 'Level 20+'],
    utilityTags: ['burst', 'wave_clear', 'stun', 'initiation', 'mobility', 'scaling'],
    needs: ['early support', 'spell combo knowledge'],
  },
  faceless_void: {
    preferredRoles: ['carry'],
    strengths: ['Chronosphere teamfight control', 'High right-click DPS', 'Backtrack evasion'],
    weaknesses: ['Can trap allies in Chrono', 'Item-dependent', 'Weak without farm'],
    powerSpikes: ['Level 6 (Chronosphere)', 'Maelstrom / MKB', 'Full items'],
    utilityTags: ['lockdown', 'scaling', 'burst', 'roshan'],
    needs: ['setup supports', 'AoE follow-up inside Chrono', 'time to farm'],
  },
  tidehunter: {
    preferredRoles: ['offlane'],
    strengths: ['Ravage teamfight ultimate', 'Good lane presence', 'Natural tankiness'],
    weaknesses: ['Ravage countered by BKB', 'Slow', 'Limited damage late'],
    powerSpikes: ['Level 6 (Ravage)', 'Blink Dagger', 'Aghanim\'s Shard'],
    utilityTags: ['stun', 'initiation', 'wave_clear', 'lockdown', 'aura_carrier'],
    needs: ['high-damage cores', 'follow-up AoE'],
  },
  lich: {
    preferredRoles: ['hard_support'],
    strengths: ['Strong laning with Sacrifice', 'Frost Shield protection', 'Chain Frost teamfight'],
    weaknesses: ['Squishy', 'No escape', 'Chain Frost can miss'],
    powerSpikes: ['Level 6 (Chain Frost)', 'Aghanim\'s Scepter', 'Aghanim\'s Shard'],
    utilityTags: ['stun', 'aura_carrier', 'wave_clear', 'save'],
    needs: ['front-line', 'initiation', 'carries to protect'],
  },
  enigma: {
    preferredRoles: ['offlane', 'support'],
    strengths: ['Black Hole game-winning teamfight', 'Creep summoning', 'Strong jungler'],
    weaknesses: ['Channeled ultimate countered by BKB', 'Item-dependent'],
    powerSpikes: ['Blink Dagger', 'Level 6 (Black Hole)', 'Aghanim\'s Scepter'],
    utilityTags: ['initiation', 'lockdown', 'wave_clear', 'roshan'],
    needs: ['high-damage follows', 'heroes that can use Eidolons'],
  },
  naga_siren: {
    preferredRoles: ['carry'],
    strengths: ['Song of the Siren buyback prevention', 'Illusion army', 'Strong splitpush'],
    weaknesses: ['Weak laner', 'Needs farm', 'Countered by AoE'],
    powerSpikes: ['Diffusal Blade', 'Level 6 (Song)', 'Full item build'],
    utilityTags: ['scaling', 'lockdown', 'mobility'],
    needs: ['early support', 'AoE protection', 'time to farm'],
  },
  furion: {
    preferredRoles: ['offlane', 'support'],
    strengths: ['Global presence', 'Strong split push', 'Tower pressure', 'Summon treants'],
    weaknesses: ['Squishy', 'Predictable patterns', 'Weak in direct teamfights'],
    powerSpikes: ['Level 6 (Wrath of Nature)', 'Aghanim\'s Scepter', 'Dagger / Force Staff'],
    utilityTags: ['tower_damage', 'wave_clear', 'mobility', 'vision'],
    needs: ['teamfight follow-up', 'reliable stuns'],
  },
  omniknight: {
    preferredRoles: ['support'],
    strengths: ['Strong healer', 'Guardian Angel magic immunity', 'Good laner', 'Repel dispel'],
    weaknesses: ['No mobility', 'Guardian Angel countered by pure damage'],
    powerSpikes: ['Level 6 (Guardian Angel)', 'Aghanim\'s Scepter', 'Aether Lens'],
    utilityTags: ['heal', 'save', 'dispel', 'aura_carrier'],
    needs: ['right-click carry to protect', 'frontline tank'],
  },
  shredder: {
    preferredRoles: ['offlane', 'mid'],
    strengths: ['Hard to kill in trees', 'Good lane harassment', 'Reactive Armor tankiness', 'Chakram damage'],
    weaknesses: ['Slow', 'Limited escape', 'Falls off late'],
    powerSpikes: ['Level 6 (Flamethrower)', 'Blade Mail', 'Aghanim\'s Scepter'],
    utilityTags: ['lane_pressure', 'burst', 'initiation'],
    needs: ['reliable stuns', 'follow-up damage'],
  },
  bristleback: {
    preferredRoles: ['offlane'],
    strengths: ['Extremely hard to kill from behind', 'Strong lane presence', 'Stacks damage with Quills'],
    weaknesses: ['Weak from the front', 'Slow', 'Falls off late'],
    powerSpikes: ['Cloak (survivability)', 'Level 6', 'Vanguard + Blade Mail'],
    utilityTags: ['lane_pressure', 'scaling'],
    needs: ['save support', 'damage follow-up'],
  },
  tusk: {
    preferredRoles: ['support'],
    strengths: ['Strong ganker', 'Walrus PUNCH kill shot', 'Tag Team snowball', 'Good roamer'],
    weaknesses: ['Squishy', 'Falls off late', 'No wave clear'],
    powerSpikes: ['Level 6 (Walrus PUNCH)', 'Blink Dagger', 'Aghanim\'s Shard'],
    utilityTags: ['stun', 'initiation', 'burst', 'mobility'],
    needs: ['high-damage cores', 'follow-up lockdown'],
  },
  skywrath_mage: {
    preferredRoles: ['support', 'mid'],
    strengths: ['Huge magic burst', 'Strong lane harass', 'Silence', 'Mystic Flare damage'],
    weaknesses: ['Squishy', 'No escape', 'Mana-hungry'],
    powerSpikes: ['Level 6 (Mystic Flare)', 'Aether Lens', 'Octarine Core'],
    utilityTags: ['burst', 'silence', 'stun', 'lane_pressure'],
    needs: ['front-line', 'initiation', 'physical damage carrier'],
  },
  abaddon: {
    preferredRoles: ['support', 'carry'],
    strengths: ['Aphotic Shield dispel', 'Mist Coil heal/nuke', 'Borrowed Time invincibility', 'Tanky'],
    weaknesses: ['No mobility', 'Weak initiation', 'Limited offensive damage'],
    powerSpikes: ['Level 6 (Borrowed Time)', 'Aghanim\'s Scepter', 'Radiance (carry)'],
    utilityTags: ['save', 'dispel', 'heal', 'aura_carrier'],
    needs: ['right-click carry to heal', 'aggressive front-liner'],
  },
  elder_titan: {
    preferredRoles: ['support'],
    strengths: ['Armor reduction aura', 'Echo Stomp stun', 'Earth Splitter teamfight'],
    weaknesses: ['Slow', 'Skill-shot reliant', 'Long cooldowns'],
    powerSpikes: ['Level 6 (Earth Splitter)', 'Blink Dagger', 'Aghanim\'s Scepter'],
    utilityTags: ['stun', 'initiation', 'lockdown', 'aura_carrier'],
    needs: ['physical damage cores', 'follow-up after armor reduction'],
  },
  legion_commander: {
    preferredRoles: ['offlane', 'support'],
    strengths: ['Duel snowballs strongly', 'Good ganker', 'Overwhelming Odds AOE', 'High mobility'],
    weaknesses: ['Falls behind without duels', 'Countered by BKB', 'Item-dependent'],
    powerSpikes: ['Dagger + Duel combo', 'Level 6', 'First few successful duels'],
    utilityTags: ['burst', 'initiation', 'lane_pressure', 'mobility'],
    needs: ['reliable stuns', 'isolation for Duel'],
  },
  techies: {
    preferredRoles: ['support', 'mid'],
    strengths: ['Zone control with mines', 'High burst', 'Map denial', 'Stasis Trap lockdown'],
    weaknesses: ['Unique playstyle', 'Weak in direct teamfights', 'Countered by scouting'],
    powerSpikes: ['Level 6', 'Dagon', 'Aghanim\'s Scepter'],
    utilityTags: ['burst', 'stun', 'vision', 'wave_clear'],
    needs: ['vision', 'sentry counters for enemy wards'],
  },
  ember_spirit: {
    preferredRoles: ['mid'],
    strengths: ['Extremely mobile', 'High burst combo', 'Strong in teamfights', 'Hard to pin down'],
    weaknesses: ['Squishy', 'Needs farm to be effective', 'Falls behind against catch'],
    powerSpikes: ['Level 6', 'Level 12 (Fire Remnant max)', 'Maelstrom'],
    utilityTags: ['burst', 'mobility', 'wave_clear', 'scaling'],
    needs: ['setup supports', 'space to farm'],
  },
  earth_spirit: {
    preferredRoles: ['support'],
    strengths: ['Strong single-target lockdown', 'Good ganker', 'Rolling Boulder mobility', 'Versatile'],
    weaknesses: ['Stone remnant management', 'Complex mechanics', 'Falls off without items'],
    powerSpikes: ['Level 6 (Magnetize)', 'Blink Dagger', 'Aghanim\'s Scepter'],
    utilityTags: ['stun', 'lockdown', 'initiation', 'silence', 'mobility'],
    needs: ['follow-up burst', 'coordinated ganks'],
  },
  abyssal_underlord: {
    preferredRoles: ['offlane'],
    strengths: ['Strong lane bully', 'Pit of Malice lockdown', 'Dark Rift global teleport', 'Tanky'],
    weaknesses: ['Slow', 'Limited solo kill potential late', 'Item-dependent'],
    powerSpikes: ['Level 6 (Dark Rift)', 'Blademail + Vanguard', 'Aghanim\'s Scepter'],
    utilityTags: ['stun', 'lockdown', 'initiation', 'mobility', 'aura_carrier'],
    needs: ['high-damage carries', 'setup for Dark Rift teleport'],
  },
  terrorblade: {
    preferredRoles: ['carry'],
    strengths: ['Strongest illusion carry', 'Sunder role-reversal', 'Hyper-scaling', 'Metamorphosis range'],
    weaknesses: ['Weak laner', 'Needs farm', 'Countered by AoE'],
    powerSpikes: ['Manta Style', 'Level 6 (Sunder)', 'Dragon Lance + Manta'],
    utilityTags: ['scaling', 'burst', 'mobility'],
    needs: ['early support', 'AoE protection', 'farm security'],
  },
  phoenix: {
    preferredRoles: ['support', 'offlane'],
    strengths: ['Strong teamfight with Supernova', 'Icarus Dive mobility', 'AoE Sun Ray', 'Fire Spirits slow'],
    weaknesses: ['Channeled ultimate easily interrupted', 'Mana-hungry', 'Squishy'],
    powerSpikes: ['Level 6 (Supernova)', 'Aghanim\'s Scepter', 'Refresher Orb'],
    utilityTags: ['stun', 'initiation', 'heal', 'wave_clear', 'burst'],
    needs: ['BKB protection cover', 'follow-up in Supernova'],
  },
  oracle: {
    preferredRoles: ['hard_support'],
    strengths: ['Incredible save toolkit', 'Fortune\'s End purge + stun', 'Fate\'s Edict invulnerability', 'False Promise'],
    weaknesses: ['Complex mechanics', 'No damage', 'Squishy'],
    powerSpikes: ['Level 6 (False Promise)', 'Aether Lens', 'Aghanim\'s Scepter'],
    utilityTags: ['save', 'dispel', 'stun', 'heal'],
    needs: ['carry to protect', 'high-value target for False Promise'],
  },
  winter_wyvern: {
    preferredRoles: ['support'],
    strengths: ['Arctic Burn long-range poke', 'Cold Embrace save', 'Winter\'s Curse AoE stun'],
    weaknesses: ['Low damage output', 'Squishy', 'Countered by spread lineup'],
    powerSpikes: ['Level 6 (Winter\'s Curse)', 'Aghanim\'s Scepter', 'Aether Lens'],
    utilityTags: ['save', 'stun', 'lockdown', 'heal'],
    needs: ['AoE damage to maximize Curse', 'physical damage cores'],
  },
  arc_warden: {
    preferredRoles: ['carry', 'mid'],
    strengths: ['Tempest Double gives two of everything', 'Strong split push', 'Hyper-carry potential'],
    weaknesses: ['Mechanically demanding', 'Weak early game', 'Item-dependent'],
    powerSpikes: ['Level 6 (Tempest Double)', 'Maelstrom + Aghanim\'s Scepter', 'Full items'],
    utilityTags: ['scaling', 'tower_damage', 'burst'],
    needs: ['early protection', 'time to scale'],
  },
  underlord: {
    preferredRoles: ['offlane'],
    strengths: ['Strong laner', 'Good teamfighter', 'Dark Rift global presence', 'Atrophy Aura'],
    weaknesses: ['Slow', 'Limited escape', 'Falls off late game'],
    powerSpikes: ['Level 6 (Dark Rift)', 'Pipe of Insight', 'Aghanim\'s Scepter'],
    utilityTags: ['stun', 'aura_carrier', 'lockdown', 'wave_clear'],
    needs: ['mobile allies to teleport with Dark Rift'],
  },
  monkey_king: {
    preferredRoles: ['carry', 'mid'],
    strengths: ['High single-target burst', 'Tree mobility', 'Wukong\'s Command teamfight', 'Good laner'],
    weaknesses: ['Falls off without Blink items', 'Countered by detection', 'Skill-shot reliant'],
    powerSpikes: ['Level 6 (Wukong\'s Command)', 'Blink Dagger', 'Echo Sabre'],
    utilityTags: ['burst', 'mobility', 'initiation', 'lane_pressure'],
    needs: ['setup stuns', 'heroes to hold enemies in Wukong\'s Command'],
  },
  dark_willow: {
    preferredRoles: ['support'],
    strengths: ['Strong lockdown combo', 'Terrorize fear', 'Cursed Crown stun', 'Bedlam teamfight'],
    weaknesses: ['Squishy', 'Combo setup required', 'Long cooldowns'],
    powerSpikes: ['Level 6 (Terrorize)', 'Aether Lens', 'Aghanim\'s Scepter'],
    utilityTags: ['stun', 'lockdown', 'burst', 'mobility', 'wave_clear'],
    needs: ['follow-up physical damage', 'setup initiation'],
  },
  pangolier: {
    preferredRoles: ['mid', 'offlane', 'support'],
    strengths: ['Shield Crash AoE', 'Rolling Thunder engage/disengaged', 'Swashbuckle damage', 'Versatile'],
    weaknesses: ['Predictable with Rolling Thunder', 'Countered by stasis/stun', 'Item-dependent'],
    powerSpikes: ['Level 6 (Rolling Thunder)', 'Aghanim\'s Scepter', 'Blink Dagger'],
    utilityTags: ['burst', 'initiation', 'stun', 'mobility', 'wave_clear'],
    needs: ['heroes to lock in Rolling Thunder path', 'follow-up damage'],
  },
  grimstroke: {
    preferredRoles: ['support', 'hard_support'],
    strengths: ['Ink Swell AoE stun', 'Stroke of Fate wave clear', 'Soulbind disables combo', 'Global reach'],
    weaknesses: ['Squishy', 'No escape', 'Dependent on ally combos for Soulbind'],
    powerSpikes: ['Level 6 (Soulbind)', 'Aether Lens', 'Aghanim\'s Scepter'],
    utilityTags: ['stun', 'lockdown', 'wave_clear', 'burst', 'silence'],
    needs: ['strong lockdown allies to combo Soulbind', 'physical damage cores'],
  },
  mars: {
    preferredRoles: ['offlane'],
    strengths: ['Arena of Blood teamfight', 'Strong initiator', 'Bulwark front-line', 'Good laner'],
    weaknesses: ['Arena countered by flying heroes', 'Falls off very late', 'Limited escape'],
    powerSpikes: ['Level 6 (Arena of Blood)', 'Blink Dagger', 'Spear of Mars + Arena combo'],
    utilityTags: ['stun', 'initiation', 'lockdown', 'wave_clear', 'lane_pressure'],
    needs: ['AoE damage inside Arena', 'setup supports'],
  },
  snapfire: {
    preferredRoles: ['support'],
    strengths: ['Scatterblast slow+damage', 'Mortimer Kisses AoE', 'Firesnap Cookie save/initiate', 'Global cookie'],
    weaknesses: ['Squishy', 'Mortimer Kisses hard to land', 'No direct escape'],
    powerSpikes: ['Level 6 (Mortimer Kisses)', 'Aghanim\'s Scepter', 'Aghanim\'s Shard'],
    utilityTags: ['burst', 'stun', 'save', 'wave_clear', 'mobility'],
    needs: ['front-line', 'physical damage cores'],
  },
  void_spirit: {
    preferredRoles: ['mid'],
    strengths: ['High mobility', 'Astral Step evasion', 'Resonant Pulse shield', 'Good dueler'],
    weaknesses: ['Squishy', 'Falls off without farm', 'Skill-dependent'],
    powerSpikes: ['Level 6 (Astral Step)', 'Kaya + Orchid', 'Level 18+'],
    utilityTags: ['burst', 'mobility', 'lockdown', 'silence'],
    needs: ['early support', 'time to scale'],
  },
  hoodwink: {
    preferredRoles: ['support'],
    strengths: ['Acorn Shot slow chain', 'Bushwhack tree stun', 'Sharpshooter long-range burst', 'Good chaser'],
    weaknesses: ['Tree-dependent for some spells', 'Squishy', 'No direct escape without trees'],
    powerSpikes: ['Level 6 (Sharpshooter)', 'Aether Lens', 'Aghanim\'s Shard'],
    utilityTags: ['stun', 'burst', 'mobility', 'vision', 'lockdown'],
    needs: ['follow-up physical damage', 'vision tools'],
  },
  dawnbreaker: {
    preferredRoles: ['offlane', 'support'],
    strengths: ['Starbreaker strong initiation', 'Celestial Hammer ranged poke', 'Solar Guardian global ultimate'],
    weaknesses: ['Squishy for a STR hero', 'Predictable patterns', 'Item-dependent'],
    powerSpikes: ['Level 6 (Solar Guardian)', 'Blink Dagger', 'Aghanim\'s Scepter'],
    utilityTags: ['stun', 'initiation', 'heal', 'mobility', 'burst'],
    needs: ['follow-up damage', 'carries to support with Solar Guardian'],
  },
  marci: {
    preferredRoles: ['support'],
    strengths: ['Rebound mobility initiation', 'Sidekick buff to carry', 'Unleash massive damage burst', 'Good stunner'],
    weaknesses: ['Item-dependent', 'High skill ceiling', 'Falls off without items'],
    powerSpikes: ['Level 6 (Unleash)', 'Blink Dagger', 'Aghanim\'s Scepter'],
    utilityTags: ['stun', 'initiation', 'mobility', 'burst', 'save'],
    needs: ['carries to buff with Sidekick', 'follow-up physical damage'],
  },
  primal_beast: {
    preferredRoles: ['offlane', 'mid'],
    strengths: ['Overwhelming Roar AoE stun', 'Onslaught charge initiation', 'Trample damage', 'Tanky'],
    weaknesses: ['Limited escape', 'Countered by kiting', 'Falls off very late'],
    powerSpikes: ['Level 6 (Pulverize)', 'Blink Dagger', 'Aghanim\'s Scepter'],
    utilityTags: ['stun', 'initiation', 'lockdown', 'lane_pressure'],
    needs: ['high-damage follows after stun', 'AoE damage cores'],
  },
  muerta: {
    preferredRoles: ['carry', 'mid'],
    strengths: ['Pierce the Veil physical-to-magic', 'Strong late game', 'Dead Shot disable', 'Lifesteal from skills'],
    weaknesses: ['Item-dependent', 'Squishy', 'Weak laner'],
    powerSpikes: ['Level 6 (Pierce the Veil)', 'Silver Edge', 'Full item build'],
    utilityTags: ['burst', 'scaling', 'lockdown', 'lane_pressure'],
    needs: ['early protection', 'setup supports'],
  },
  ringmaster: {
    preferredRoles: ['support'],
    strengths: ['Tame the Beasts buffs team', 'The Box AoE lockdown', 'Wheel of Wonder global'],
    weaknesses: ['Requires coordination', 'Complex kit', 'Long cooldowns'],
    powerSpikes: ['Level 6 (Wheel of Wonder)', 'Aghanim\'s Scepter', 'Aether Lens'],
    utilityTags: ['stun', 'save', 'lockdown', 'heal'],
    needs: ['follow-up damage', 'carries to buff'],
  },
  // Additional heroes with basic metadata
  chen: {
    preferredRoles: ['support'],
    strengths: ['Creep control for strong early game', 'Holy Persuasion utility', 'Hand of God global heal', 'Aggressive jungler'],
    weaknesses: ['Micro-intensive', 'Falls off without creeps', 'Squishy'],
    powerSpikes: ['Level 6 (Hand of God)', 'Ancient creeps', 'Aghanim\'s Scepter'],
    utilityTags: ['heal', 'save', 'mobility', 'lockdown'],
    needs: ['high-damage carries to heal', 'fast-push potential'],
  },
  clinkz: {
    preferredRoles: ['carry', 'mid'],
    strengths: ['High single-target damage', 'Searing Arrows amplify', 'Skeleton Walk invisibility', 'Strong sieging'],
    weaknesses: ['Squishy', 'Struggles in teamfights', 'Item-dependent'],
    powerSpikes: ['Orchid Malevolence', 'Level 6 (Death Pact)', 'Aghanim\'s Scepter'],
    utilityTags: ['burst', 'silence', 'tower_damage', 'mobility', 'vision'],
    needs: ['setup stuns', 'front-line tank'],
  },
  dark_seer: {
    preferredRoles: ['offlane'],
    strengths: ['Wall of Replica illusion teamfight', 'Vacuum + Wall combo', 'Ion Shell farming', 'Surge speed'],
    weaknesses: ['Low base damage', 'Requires vacuum combo to be impactful', 'Predictable'],
    powerSpikes: ['Level 6 (Wall of Replica)', 'Blink Dagger', 'Pipe of Insight'],
    utilityTags: ['initiation', 'lockdown', 'mobility', 'wave_clear', 'aura_carrier'],
    needs: ['AoE follow-up inside Wall + Vacuum', 'right-click carries'],
  },
  death_prophet: {
    preferredRoles: ['mid', 'offlane'],
    strengths: ['Exorcism powerful ultimate', 'Carrion Swarm nukes', 'Spirit Siphon sustain', 'Pushes well'],
    weaknesses: ['Channeled Exorcism requires protection', 'Item-dependent', 'No real escape'],
    powerSpikes: ['Level 6 (Exorcism)', 'Aghanim\'s Scepter', 'Aghanim\'s Shard'],
    utilityTags: ['burst', 'wave_clear', 'tower_damage', 'heal'],
    needs: ['BKB protection', 'front-line to allow Exorcism channels'],
  },
  disruptor: {
    preferredRoles: ['support'],
    strengths: ['Glimpse teleport counter', 'Thunder Strike harass', 'Static Storm silence + damage', 'Kinetic Field cage'],
    weaknesses: ['Squishy', 'Glimpse useless vs no teleport', 'No escape'],
    powerSpikes: ['Level 6 (Static Storm)', 'Aghanim\'s Scepter', 'Aether Lens'],
    utilityTags: ['silence', 'lockdown', 'stun', 'burst', 'vision'],
    needs: ['physical damage inside Kinetic Field', 'initiation to set up Field'],
  },
  doom_bringer: {
    preferredRoles: ['offlane', 'carry'],
    strengths: ['Doom silences key heroes', 'Scorched Earth sustain + speed', 'Devour for farm', 'Strong laner'],
    weaknesses: ['Slow', 'Doom countered by Linken\'s', 'No escape'],
    powerSpikes: ['Level 6 (Doom)', 'Blink Dagger', 'Aghanim\'s Scepter'],
    utilityTags: ['silence', 'lockdown', 'burst', 'lane_pressure'],
    needs: ['damage dealers', 'heroes to follow up on Doomed enemy'],
  },
  dragon_knight: {
    preferredRoles: ['mid', 'offlane'],
    strengths: ['Very tanky with Dragon Blood', 'Dragon Form provides AoE', 'Strong tower pusher', 'Good laner'],
    weaknesses: ['Slow without Dragon Form', 'Item-dependent for late game', 'Limited mobility'],
    powerSpikes: ['Level 6 (Elder Dragon Form)', 'BKB', 'Blink Dagger'],
    utilityTags: ['stun', 'tower_damage', 'lane_pressure', 'initiation', 'scaling'],
    needs: ['save support', 'AoE damage follow-up'],
  },
  dazzle: {
    preferredRoles: ['support', 'hard_support'],
    strengths: ['Shallow Grave prevents kills', 'Shadow Wave bouncing heal/damage', 'Weave armor reduction', 'Constant saving'],
    weaknesses: ['Low damage output', 'Squishy', 'Relies on ally survival'],
    powerSpikes: ['Level 1 (Shallow Grave)', 'Aghanim\'s Scepter', 'Aghanim\'s Shard'],
    utilityTags: ['save', 'heal', 'aura_carrier', 'dispel'],
    needs: ['high-value carry to keep alive', 'physical damage dealers for Weave'],
  },
  enchantress: {
    preferredRoles: ['support', 'carry'],
    strengths: ['Enchant creep control', 'Untouchable slows', 'Nature\'s Attendants heal', 'Impetus long-range damage'],
    weaknesses: ['Squishy', 'Micro-intensive with enchanted creeps', 'Falls off without ranged hero feel'],
    powerSpikes: ['Level 6 (Impetus)', 'Solar Crest / Aghs', 'Pipe of Insight'],
    utilityTags: ['heal', 'mobility', 'lane_pressure', 'lockdown'],
    needs: ['front-line', 'setup stuns'],
  },
  gyrocopter: {
    preferredRoles: ['carry', 'mid'],
    strengths: ['Flak Cannon multi-target', 'Call Down teamfight', 'Good early game', 'Rocket Barrage burst'],
    weaknesses: ['Low HP pool', 'No escape', 'Item-dependent'],
    powerSpikes: ['Level 6 (Call Down)', 'Aghanim\'s Scepter', 'Daedalus'],
    utilityTags: ['burst', 'wave_clear', 'tower_damage', 'lane_pressure'],
    needs: ['peel support', 'initiation', 'front-line'],
  },
  huskar: {
    preferredRoles: ['mid', 'offlane'],
    strengths: ['Life Break gap closer', 'Very strong vs magic damage lineups', 'High lane dominance', 'Inner Vitality'],
    weaknesses: ['Very low HP while attacking (risky)', 'Countered by magic burst and armor', 'Item-dependent'],
    powerSpikes: ['Level 6 (Life Break)', 'Armlet of Mordiggian', 'Aghanim\'s Scepter'],
    utilityTags: ['burst', 'initiation', 'lane_pressure', 'scaling'],
    needs: ['save support (Oracle / Dazzle)', 'strong lane phase'],
  },
  jakiro: {
    preferredRoles: ['support', 'hard_support'],
    strengths: ['Macropyre strong teamfight', 'Dual Breath slow + damage', 'Ice Path long stun', 'Good pusher'],
    weaknesses: ['Slow', 'Squishy', 'Long cooldowns early'],
    powerSpikes: ['Level 6 (Macropyre)', 'Aghanim\'s Scepter', 'Aghanim\'s Shard'],
    utilityTags: ['stun', 'wave_clear', 'burst', 'tower_damage', 'lockdown'],
    needs: ['initiation', 'physical damage inside Macropyre'],
  },
  keeper_of_the_light: {
    preferredRoles: ['support'],
    strengths: ['Illuminate lane clear and poke', 'Chakra Magic mana restore', 'Will-O-Wisp teamfight fear'],
    weaknesses: ['No reliable disable', 'Squishy', 'Illuminate telegraphed'],
    powerSpikes: ['Level 6 (Will-O-Wisp)', 'Aghanim\'s Scepter', 'Refresher Orb'],
    utilityTags: ['wave_clear', 'burst', 'vision', 'heal'],
    needs: ['lockdown allies', 'physical damage carries'],
  },
  leshrac: {
    preferredRoles: ['mid', 'support'],
    strengths: ['Lightning Storm fast clear', 'Diabolic Edict tower damage', 'Pulse Nova teamfight', 'Split Earth stun'],
    weaknesses: ['Squishy', 'No escape', 'Mana-hungry'],
    powerSpikes: ['Level 6 (Pulse Nova)', 'Aghanim\'s Scepter', 'BKB'],
    utilityTags: ['burst', 'stun', 'tower_damage', 'wave_clear', 'lane_pressure'],
    needs: ['save support', 'front-line', 'BKB to stay alive in Pulse Nova'],
  },
  lone_druid: {
    preferredRoles: ['carry', 'offlane'],
    strengths: ['Spirit Bear tanky pusher', 'True Form teamfight', 'Strong split push', 'Bear Claw items'],
    weaknesses: ['Micro-intensive', 'Weak without Bear', 'Slow movement speed'],
    powerSpikes: ['Level 6 (True Form)', 'Phase Boots + Orb on Bear', 'Full Bear items'],
    utilityTags: ['tower_damage', 'wave_clear', 'scaling', 'initiation'],
    needs: ['AoE support', 'reliable stuns'],
  },
  luna: {
    preferredRoles: ['carry'],
    strengths: ['High attack speed with Lucent Beam procs', 'Eclipse massive AoE', 'Moon Glaive farming', 'Aura carrier'],
    weaknesses: ['Squishy', 'Item-dependent', 'Falls behind if no farm'],
    powerSpikes: ['Level 6 (Eclipse)', 'Aghanim\'s Scepter', 'Dragon Lance + Manta'],
    utilityTags: ['burst', 'aura_carrier', 'wave_clear', 'scaling'],
    needs: ['initiation', 'peel support', 'front-line'],
  },
  lycan: {
    preferredRoles: ['carry', 'offlane'],
    strengths: ['Massive push with Wolves + Shapeshift', 'Strong early game', 'Good Roshan', 'Howl team buff'],
    weaknesses: ['Day/Night cycle dependency', 'Countered by AoE', 'Focused easily'],
    powerSpikes: ['Level 6 (Shapeshift)', 'Helm of the Overlord', 'Aghanim\'s Scepter'],
    utilityTags: ['tower_damage', 'roshan', 'wave_clear', 'aura_carrier'],
    needs: ['save support', 'coordination for fast pushes'],
  },
  magnus: {
    preferredRoles: ['offlane', 'support'],
    strengths: ['Reverse Polarity massive AoE stun', 'Empower damage buff for team', 'Skewer engage'],
    weaknesses: ['Falls off solo', 'Relies on follow-up', 'Blink-dependent'],
    powerSpikes: ['Blink Dagger', 'Level 6 (Reverse Polarity)', 'Aghanim\'s Scepter'],
    utilityTags: ['stun', 'initiation', 'lockdown', 'aura_carrier'],
    needs: ['AoE damage follow-up', 'Chrono / Black Hole / Ravage combo'],
  },
  medusa: {
    preferredRoles: ['carry'],
    strengths: ['Insanely tanky with Mana Shield', 'Stone Gaze in teamfights', 'Split Shot farming', 'Hyper-carry'],
    weaknesses: ['Very slow farmer early', 'Needs massive farm', 'Weak laner'],
    powerSpikes: ['Manta Style', 'Aghanim\'s Scepter', 'Full items (45+ min)'],
    utilityTags: ['scaling', 'lockdown', 'roshan'],
    needs: ['heavy support', 'time to farm', 'early game carry from team'],
  },
  meepo: {
    preferredRoles: ['mid', 'offlane'],
    strengths: ['Multiple poof clones', 'Earthbind lockdown', 'Strong split push', 'Highest skill snowball'],
    weaknesses: ['Very mechanically demanding', 'Any death kills all clones (Aghs)', 'Countered by AoE'],
    powerSpikes: ['Level 4 (second Meepo)', 'Aghanim\'s Scepter', 'Level 12 (four Meepos)'],
    utilityTags: ['lockdown', 'scaling', 'tower_damage', 'mobility'],
    needs: ['strong laning support', 'AoE protection'],
  },
  nyx_assassin: {
    preferredRoles: ['support'],
    strengths: ['Impale stun', 'Spiked Carapace reflect', 'Vendetta invisibility ganks', 'Mana Burn vs INT'],
    weaknesses: ['Low armor', 'Falls off late game', 'No wave clear'],
    powerSpikes: ['Level 6 (Vendetta)', 'Blink Dagger', 'Aghanim\'s Scepter'],
    utilityTags: ['stun', 'burst', 'initiation', 'mobility'],
    needs: ['physical damage follow-up', 'reliable lockdown'],
  },
  ogre_magi: {
    preferredRoles: ['support'],
    strengths: ['Very tanky for a support', 'Ignite + Fireblast stun', 'Multicast RNG', 'Good laner'],
    weaknesses: ['Slow', 'RNG-dependent', 'Falls off late'],
    powerSpikes: ['Level 6 (Multicast)', 'Aghanim\'s Scepter', 'Level 25 talent'],
    utilityTags: ['stun', 'lane_pressure', 'burst', 'aura_carrier'],
    needs: ['physical damage carries', 'AoE follow-up'],
  },
  phantom_assassin: {
    preferredRoles: ['carry'],
    strengths: ['Blur evasion', 'Coup de Grace high crit', 'Stifling Dagger slow', 'Blink Strike mobility'],
    weaknesses: ['Countered by True Strike (MKB)', 'Needs BKB vs heavy magic', 'Item-dependent'],
    powerSpikes: ['Blink Strike level', 'Battle Fury', 'Desolator + Daedalus'],
    utilityTags: ['burst', 'mobility', 'scaling'],
    needs: ['setup stuns', 'BKB cover', 'front-line tank'],
  },
  pugna: {
    preferredRoles: ['mid', 'support'],
    strengths: ['Nether Blast tower damage', 'Decrepify setups', 'Life Drain sustain', 'Strong with magic damage'],
    weaknesses: ['Squishy', 'No escape', 'Countered by magic immunity'],
    powerSpikes: ['Level 6 (Life Drain)', 'Aghanim\'s Scepter', 'Ethereal Blade'],
    utilityTags: ['burst', 'wave_clear', 'tower_damage', 'heal'],
    needs: ['magic damage allies for Decrepify setup', 'front-line'],
  },
  queen_of_pain: {
    preferredRoles: ['mid'],
    strengths: ['Blink short CD escape/engage', 'Scream of Pain AoE', 'Sonic Wave teamfight', 'Strong ganker'],
    weaknesses: ['Squishy', 'Mana-hungry', 'Countered by silence'],
    powerSpikes: ['Level 6 (Sonic Wave)', 'Kaya', 'Aghanim\'s Scepter'],
    utilityTags: ['burst', 'mobility', 'wave_clear', 'lane_pressure'],
    needs: ['peel support', 'physical damage carry'],
  },
  riki: {
    preferredRoles: ['carry'],
    strengths: ['Permanent invisibility', 'Tricks of the Trade AoE', 'Good ganker', 'Diffusal Blade synergy'],
    weaknesses: ['Countered by detection/Dust', 'Weak in direct fights vs detection', 'Item-dependent'],
    powerSpikes: ['Level 6 (Tricks of the Trade)', 'Diffusal Blade', 'Aghanim\'s Scepter'],
    utilityTags: ['burst', 'mobility', 'silence'],
    needs: ['reliable stuns', 'invisibility coordination'],
  },
  rubick: {
    preferredRoles: ['support'],
    strengths: ['Spell steal changes every fight', 'Telekinesis setup', 'Fade Bolt reduces damage', 'Versatile'],
    weaknesses: ['Squishy', 'Stolen spell requires enemy to have good ultimate'],
    powerSpikes: ['Level 6 (Spell Steal)', 'Aether Lens', 'Aghanim\'s Scepter'],
    utilityTags: ['stun', 'lockdown', 'initiation', 'burst', 'save'],
    needs: ['enemy lineup with stealable ultimates', 'follow-up'],
  },
  shadow_demon: {
    preferredRoles: ['support'],
    strengths: ['Disruption displacement', 'Shadow Poison poke', 'Demonic Purge strong slow', 'Good ganker'],
    weaknesses: ['Squishy', 'Illusions from Disruption can backfire', 'Item-dependent'],
    powerSpikes: ['Level 6 (Demonic Purge)', 'Aghanim\'s Scepter', 'Aether Lens'],
    utilityTags: ['burst', 'lockdown', 'mobility', 'vision'],
    needs: ['follow-up damage', 'physical damage after Disruption'],
  },
  shadow_shaman: {
    preferredRoles: ['support'],
    strengths: ['Hex + Shackles lockdown combo', 'Mass Serpent Ward push', 'Strong lane harass', 'Tower killer'],
    weaknesses: ['Channeled Shackles easily interrupted', 'Squishy', 'No escape'],
    powerSpikes: ['Level 6 (Mass Serpent Wards)', 'Aghanim\'s Scepter', 'Blink Dagger'],
    utilityTags: ['stun', 'lockdown', 'wave_clear', 'tower_damage'],
    needs: ['initiation', 'BKB cover to Shackle', 'front-line'],
  },
  silencer: {
    preferredRoles: ['support', 'carry'],
    strengths: ['Global Silence game-changing ultimate', 'Curse of the Silent denial', 'Good laner', 'Scaling INT steal'],
    weaknesses: ['No mobility', 'Squishy', 'Global Silence countered by BKB'],
    powerSpikes: ['Level 6 (Global Silence)', 'Aghanim\'s Scepter', 'Aghanim\'s Shard'],
    utilityTags: ['silence', 'burst', 'lane_pressure', 'wave_clear'],
    needs: ['physical damage follow-up during Silence', 'initiation'],
  },
  skeleton_king: {
    preferredRoles: ['carry', 'offlane'],
    strengths: ['Reincarnation second life', 'Hellfire Blast stun', 'Vampiric Aura team lifesteal', 'Strong laner'],
    weaknesses: ['Slow attack speed without Mortal Strike', 'Item-dependent', 'Easy to kite'],
    powerSpikes: ['Level 6 (Reincarnation)', 'Armlet of Mordiggian', 'Assault Cuirass'],
    utilityTags: ['stun', 'aura_carrier', 'scaling', 'roshan'],
    needs: ['reliable stuns', 'front-line to proc Hellfire Blast'],
  },
  spectre: {
    preferredRoles: ['carry'],
    strengths: ['Haunt global presence', 'Desolate vs isolated targets', 'Dispersion survivability', 'Strong late game'],
    weaknesses: ['Very weak early game', 'Needs farm', 'Slow to come online'],
    powerSpikes: ['Radiance', 'Level 6 (Haunt)', 'Diffusal Blade + Manta'],
    utilityTags: ['scaling', 'mobility', 'burst'],
    needs: ['heavy early support', 'defensive play early', 'time to farm'],
  },
  spirit_breaker: {
    preferredRoles: ['support', 'offlane'],
    strengths: ['Charge of Darkness global initiation', 'Nether Strike stun', 'Bulldoze unstoppable', 'Great chaser'],
    weaknesses: ['Predictable charge', 'Countered by strong disjoints', 'Item-dependent late'],
    powerSpikes: ['Level 6 (Nether Strike)', 'Blink Dagger', 'Aghanim\'s Scepter'],
    utilityTags: ['initiation', 'stun', 'mobility', 'lockdown'],
    needs: ['follow-up damage', 'initiation coordination'],
  },
  slardar: {
    preferredRoles: ['offlane', 'support'],
    strengths: ['Slithereen Crush stun', 'Corrosive Haze armor reduction', 'Sprint mobility', 'Amplify Damage'],
    weaknesses: ['No ranged poke', 'Falls off without items', 'Relies on armor reduction'],
    powerSpikes: ['Level 6 (Corrosive Haze)', 'Blink Dagger', 'Aghanim\'s Scepter'],
    utilityTags: ['stun', 'initiation', 'aura_carrier', 'mobility'],
    needs: ['physical damage carries to benefit from armor reduction', 'follow-up stuns'],
  },
  templar_assassin: {
    preferredRoles: ['mid', 'carry'],
    strengths: ['Refraction built-in damage block', 'Psionic Trap map control', 'Meld burst damage', 'Strong laner'],
    weaknesses: ['Countered by AoE removing Refraction', 'Item-dependent', 'No escape without items'],
    powerSpikes: ['Level 6 (Psionic Trap)', 'Desolator', 'Dragon Lance + BKB'],
    utilityTags: ['burst', 'mobility', 'lane_pressure', 'vision'],
    needs: ['setup stuns', 'save support', 'isolation for Meld'],
  },
  treant_protector: {
    preferredRoles: ['support', 'hard_support'],
    strengths: ['Nature\'s Grasp strong root', 'Overgrowth AoE root ultimate', 'Living Armor heals', 'Strong laner'],
    weaknesses: ['Slow', 'Overgrowth countered by BKB', 'Limited solo kill potential'],
    powerSpikes: ['Level 6 (Overgrowth)', 'Aghanim\'s Scepter', 'Aghanim\'s Shard'],
    utilityTags: ['stun', 'lockdown', 'heal', 'save', 'wave_clear'],
    needs: ['physical damage inside Overgrowth', 'AoE damage to maximize root'],
  },
  troll_warlord: {
    preferredRoles: ['carry'],
    strengths: ['Berserker\'s Rage melee/ranged swap', 'Whirling Axes slow', 'Battle Trance massive attack speed', 'Fervor buff'],
    weaknesses: ['No escape', 'Kitable', 'Item-dependent'],
    powerSpikes: ['Level 6 (Battle Trance)', 'Battle Fury', 'Aghanim\'s Scepter'],
    utilityTags: ['burst', 'scaling', 'roshan'],
    needs: ['initiation', 'peel support', 'front-line'],
  },
  undying: {
    preferredRoles: ['support', 'offlane'],
    strengths: ['Tombstone zombies teamfight', 'Flesh Golem ultimate', 'Soul Rip heal/nuke', 'Strength steal'],
    weaknesses: ['Tombstone easily destroyed', 'Squishy early', 'Limited escape'],
    powerSpikes: ['Level 6 (Flesh Golem)', 'Aghanim\'s Scepter', 'Tombstone + items'],
    utilityTags: ['heal', 'stun', 'burst', 'wave_clear'],
    needs: ['physical damage', 'setup initiation'],
  },
  ursa: {
    preferredRoles: ['carry', 'offlane'],
    strengths: ['Extremely strong vs Roshan', 'Enrage damage reduction', 'Earthshock slow', 'Strong dueler'],
    weaknesses: ['Easy to kite', 'Item-dependent', 'Falls off in large teamfights'],
    powerSpikes: ['Level 6 (Enrage)', 'Blink Dagger + BKB', 'Early Roshan'],
    utilityTags: ['burst', 'roshan', 'initiation', 'lane_pressure'],
    needs: ['initiation support', 'help getting early Roshan'],
  },
  viper: {
    preferredRoles: ['mid', 'offlane', 'carry'],
    strengths: ['Extremely strong laner', 'Poison Attack slow', 'Viper Strike strong slow', 'Corrosive Skin'],
    weaknesses: ['Falls off extremely late', 'No mobility', 'Countered by magic immunity'],
    powerSpikes: ['Level 6 (Viper Strike)', 'Aghanim\'s Scepter', 'Level 12'],
    utilityTags: ['lane_pressure', 'burst', 'lockdown'],
    needs: ['save support', 'strong early and mid game'],
  },
  visage: {
    preferredRoles: ['support', 'mid'],
    strengths: ['Familiars high burst', 'Gravekeepers Cloak tankiness', 'Soul Assumption damage', 'Good laner'],
    weaknesses: ['Familiars require micro', 'Squishy without Cloak stacks', 'Complex mechanics'],
    powerSpikes: ['Level 6 (Summon Familiars)', 'Aghanim\'s Scepter', 'Aghanim\'s Shard'],
    utilityTags: ['burst', 'stun', 'lockdown', 'vision'],
    needs: ['physical damage carry', 'follow-up'],
  },
  warlock: {
    preferredRoles: ['support'],
    strengths: ['Fatal Bonds team chain damage', 'Upheaval strong slow', 'Chaotic Offering powerful ultimate', 'Good laner'],
    weaknesses: ['Slow', 'Squishy', 'Golem Infernal requires BKB combo'],
    powerSpikes: ['Level 6 (Chaotic Offering)', 'Aghanim\'s Scepter', 'Refresher Orb'],
    utilityTags: ['stun', 'lockdown', 'burst', 'wave_clear'],
    needs: ['physical damage to amplify Fatal Bonds', 'initiation'],
  },
  weaver: {
    preferredRoles: ['carry', 'support'],
    strengths: ['Time Lapse second life', 'Shukuchi escape/mobility', 'Swarm armor reduction', 'Geminate Attack'],
    weaknesses: ['Squishy', 'Weak in direct teamfights without proper positioning', 'Item-dependent'],
    powerSpikes: ['Level 6 (Time Lapse)', 'Dragon Lance', 'Aghanim\'s Scepter'],
    utilityTags: ['mobility', 'scaling', 'burst', 'vision'],
    needs: ['setup stuns', 'front-line protection'],
  },
  // Wraith King (skeleton_king above), Zeus (zuus above)
  invoker_qw: {
    preferredRoles: ['mid'],
    strengths: ['Strong ganker build', 'Tornado + Meteor combo', 'Versatile utility', 'Hard to predict'],
    weaknesses: ['Mechanically demanding', 'Weaker teamfight vs Exort'],
    powerSpikes: ['Level 6', 'Aghanim\'s Scepter', 'Level 20'],
    utilityTags: ['burst', 'stun', 'mobility', 'wave_clear'],
    needs: ['early support', 'vision'],
  },
  io: {
    preferredRoles: ['hard_support'],
    strengths: ['Global relocate', 'Strong heal with Overcharge', 'Tether movement speed', 'Saves allies globally'],
    weaknesses: ['Extremely item-dependent', 'Useless without a strong carry', 'Hard to play'],
    powerSpikes: ['Level 6 (Relocate)', 'Mek / Holy Locket', 'Aghanim\'s Scepter'],
    utilityTags: ['save', 'heal', 'mobility', 'roshan'],
    needs: ['high-impact carry partner', 'strong laning duo'],
  },
};

// ─────────────────────────────────────────────────────────────
// Meta role and flex role tables (keyed by OpenDota short name)
// ─────────────────────────────────────────────────────────────

export const META_ROLE_MAP: Record<string, MetaRole> = {
  // Pos 1 – safe-lane carry
  antimage: 'pos1', drow_ranger: 'pos1', juggernaut: 'pos1',
  morphling: 'pos1', phantom_lancer: 'pos1', faceless_void: 'pos1',
  terrorblade: 'pos1', medusa: 'pos1', luna: 'pos1', spectre: 'pos1',
  phantom_assassin: 'pos1', weaver: 'pos1', troll_warlord: 'pos1',
  gyrocopter: 'pos1', lone_druid: 'pos1', naga_siren: 'pos1',
  ursa: 'pos1', lycan: 'pos1', skeleton_king: 'pos1', arc_warden: 'pos1',
  muerta: 'pos1', slark: 'pos1', bloodseeker: 'pos1',
  clinkz: 'pos1', meepo: 'pos1', riki: 'pos1',

  // Pos 2 – mid laner
  nevermore: 'pos2', storm_spirit: 'pos2', razor: 'pos2',
  puck: 'pos2', invoker: 'pos2', ember_spirit: 'pos2',
  void_spirit: 'pos2', zuus: 'pos2', lina: 'pos2',
  kunkka: 'pos2', dragon_knight: 'pos2', huskar: 'pos2',
  queen_of_pain: 'pos2', death_prophet: 'pos2', tinker: 'pos2',
  broodmother: 'pos2', visage: 'pos2', templar_assassin: 'pos2',
  leshrac: 'pos2', pugna: 'pos2', viper: 'pos2',

  // Pos 3 – offlaner
  axe: 'pos3', tidehunter: 'pos3', mars: 'pos3',
  sand_king: 'pos3', underlord: 'pos3', dark_seer: 'pos3',
  abyssal_underlord: 'pos3', bristleback: 'pos3', legion_commander: 'pos3',
  primal_beast: 'pos3', shredder: 'pos3', doom_bringer: 'pos3',
  slardar: 'pos3', magnus: 'pos3', enigma: 'pos3',
  phoenix: 'pos3', night_stalker: 'pos3', dawnbreaker: 'pos3',
  batrider: 'pos3', timbersaw: 'pos3', centaur: 'pos3',
  dragon_knight_offlane: 'pos3',

  // Pos 4 – roaming / soft support
  earthshaker: 'pos4', earth_spirit: 'pos4', tusk: 'pos4',
  bounty_hunter: 'pos4', nyx_assassin: 'pos4', spirit_breaker: 'pos4',
  vengefulspirit: 'pos4', clockwerk: 'pos4', pudge: 'pos4',
  lion: 'pos4', skywrath_mage: 'pos4', rubick: 'pos4',
  dark_willow: 'pos4', hoodwink: 'pos4', pangolier: 'pos4',
  monkey_king: 'pos4', marci: 'pos4', techies: 'pos4',
  shadow_shaman: 'pos4', ogre_magi: 'pos4', windrunner: 'pos4',
  disruptor: 'pos4', mirana: 'pos4', tiny: 'pos4',
  invoker_qw: 'pos4', silencer: 'pos4', snapfire: 'pos4',
  grimstroke: 'pos4',

  // Pos 5 – hard support
  crystal_maiden: 'pos5', lich: 'pos5', ancient_apparition: 'pos5',
  dazzle: 'pos5', oracle: 'pos5', winter_wyvern: 'pos5',
  omniknight: 'pos5', warlock: 'pos5', bane: 'pos5',
  abaddon: 'pos5', witch_doctor: 'pos5', chen: 'pos5',
  io: 'pos5', jakiro: 'pos5', keeper_of_the_light: 'pos5',
  shadow_demon: 'pos5', elder_titan: 'pos5', treant_protector: 'pos5',
  ringmaster: 'pos5',

  // Flex
  sven: 'flex', furion: 'flex', enchantress: 'flex',
  undying: 'flex',
};

// Additional roles a hero can viably play (beyond their primary metaRole)
export const FLEX_ROLES_MAP: Record<string, Role[]> = {
  antimage: [],
  axe: [],
  bane: ['support'],
  bloodseeker: ['offlane'],
  crystal_maiden: [],
  drow_ranger: [],
  earthshaker: ['hard_support'],
  juggernaut: [],
  mirana: ['support', 'mid'],
  morphling: [],
  nevermore: ['carry'],
  phantom_lancer: [],
  puck: ['offlane'],
  pudge: ['offlane', 'hard_support'],
  razor: ['carry', 'offlane'],
  sand_king: ['support'],
  storm_spirit: ['carry'],
  sven: ['carry', 'offlane'],
  tiny: ['support', 'carry'],
  vengefulspirit: ['hard_support'],
  windrunner: ['support', 'mid'],
  zuus: ['hard_support'],
  kunkka: ['support', 'carry'],
  lina: ['support', 'carry'],
  lion: ['hard_support'],
  witch_doctor: ['support'],
  ancient_apparition: ['support'],
  invoker: ['carry'],
  faceless_void: [],
  tidehunter: [],
  lich: [],
  enigma: ['offlane', 'support'],
  naga_siren: [],
  furion: ['support', 'offlane'],
  omniknight: ['support'],
  shredder: ['offlane', 'mid'],
  bristleback: [],
  tusk: ['offlane'],
  skywrath_mage: ['support', 'mid'],
  abaddon: ['support', 'carry'],
  elder_titan: ['support'],
  legion_commander: ['offlane', 'support'],
  techies: ['support'],
  ember_spirit: [],
  earth_spirit: ['support'],
  abyssal_underlord: ['offlane'],
  terrorblade: [],
  phoenix: ['offlane', 'support'],
  oracle: [],
  winter_wyvern: ['support'],
  arc_warden: ['mid', 'carry'],
  underlord: [],
  monkey_king: ['carry', 'mid'],
  dark_willow: ['support'],
  pangolier: ['mid', 'offlane', 'support'],
  grimstroke: ['support'],
  mars: ['offlane'],
  snapfire: ['support'],
  void_spirit: [],
  hoodwink: ['support'],
  dawnbreaker: ['offlane', 'support'],
  marci: ['support', 'offlane'],
  primal_beast: ['offlane'],
  muerta: ['mid'],
  ringmaster: ['support'],
  chen: ['support'],
  clinkz: ['mid'],
  dark_seer: ['offlane'],
  death_prophet: ['offlane'],
  disruptor: ['support', 'hard_support'],
  doom_bringer: ['offlane', 'carry'],
  dragon_knight: ['mid', 'offlane'],
  dazzle: ['support', 'hard_support'],
  enchantress: ['carry', 'support'],
  gyrocopter: ['mid', 'carry'],
  huskar: ['offlane'],
  jakiro: ['support', 'hard_support'],
  keeper_of_the_light: ['support'],
  leshrac: ['support'],
  lone_druid: ['offlane'],
  luna: ['carry'],
  lycan: ['offlane'],
  magnus: ['support'],
  medusa: [],
  meepo: ['offlane'],
  nyx_assassin: ['support'],
  ogre_magi: ['support'],
  phantom_assassin: [],
  pugna: ['support'],
  queen_of_pain: [],
  riki: ['support'],
  rubick: ['support', 'hard_support'],
  shadow_demon: ['support'],
  shadow_shaman: ['support'],
  silencer: ['support', 'carry'],
  skeleton_king: ['carry', 'offlane'],
  spectre: [],
  spirit_breaker: ['offlane'],
  slardar: ['offlane', 'support'],
  templar_assassin: ['mid'],
  treant_protector: ['support'],
  troll_warlord: [],
  undying: ['offlane', 'support'],
  ursa: ['carry'],
  viper: ['mid', 'offlane'],
  visage: ['support'],
  warlock: ['support'],
  weaver: ['support'],
  io: [],
};

// Map from OpenDota primary_attr to our Attribute type
export function mapAttr(attr: string): import('./types').Attribute {
  const map: Record<string, import('./types').Attribute> = {
    str: 'strength', agi: 'agility', int: 'intelligence', all: 'universal',
  };
  return map[attr] ?? 'universal';
}

// Map from OpenDota roles array to our Role type array
export function mapRoles(openDotaRoles: string[]): Role[] {
  const roleMap: Record<string, Role> = {
    Carry: 'carry',
    Support: 'support',
    'Nuker': 'mid',
    Disabler: 'support',
    Jungler: 'offlane',
    Durable: 'offlane',
    Escape: 'carry',
    Pusher: 'offlane',
    Initiator: 'offlane',
  };
  const result = new Set<Role>();
  for (const r of openDotaRoles) {
    const mapped = roleMap[r];
    if (mapped) result.add(mapped);
  }
  if (result.size === 0) result.add('mid');
  return [...result];
}

// Derive basic utility tags from OpenDota roles
export function deriveUtilityTags(openDotaRoles: string[]): UtilityTag[] {
  const tags = new Set<UtilityTag>();
  if (openDotaRoles.includes('Disabler')) tags.add('stun');
  if (openDotaRoles.includes('Initiator')) tags.add('initiation');
  if (openDotaRoles.includes('Support')) tags.add('heal');
  if (openDotaRoles.includes('Pusher')) tags.add('tower_damage');
  if (openDotaRoles.includes('Escape')) tags.add('mobility');
  if (openDotaRoles.includes('Carry')) tags.add('scaling');
  if (openDotaRoles.includes('Nuker')) tags.add('burst');
  if (openDotaRoles.includes('Durable')) tags.add('aura_carrier');
  if (openDotaRoles.includes('Jungler')) tags.add('wave_clear');
  return [...tags];
}
