// Per-hero mechanic profile, keyed by OpenDota short name. Drives the item
// matcher (shared/matchups.ts):
//   reliance[]   — what the hero depends on; neutralizing it (via the answering
//                  item mechanics in RELIANCE_ANSWERS) hurts them a lot.
//   vulnerable[] — extra item mechanics that directly answer the hero even though
//                  they aren't a "reliance" (e.g. slippery casters → hard_control).
//
// Hand-authored from kit knowledge. Full roster coverage; tweak as patches shift.
import type { Mechanic, Reliance } from './mechanics';

export interface HeroMechProfile {
  reliance?: Reliance[];
  vulnerable?: Mechanic[];
}

export const HERO_MECHANICS: Record<string, HeroMechProfile> = {
  antimage:        { reliance: ['right_click'], vulnerable: ['hard_control'] },
  axe:             { reliance: ['passive'] },
  bane:            { reliance: ['channel', 'single_target_spell'] },
  bloodseeker:     { reliance: ['right_click', 'passive'] },
  crystal_maiden:  { reliance: ['magic_burst', 'channel'] },
  drow_ranger:     { reliance: ['right_click', 'passive'] },
  earthshaker:     { reliance: ['magic_burst'] },
  juggernaut:      { reliance: ['right_click'] },
  mirana:          { reliance: ['right_click'] },
  morphling:       { reliance: ['right_click'], vulnerable: ['hard_control'] },
  nevermore:       { reliance: ['right_click', 'magic_burst'] },
  phantom_lancer:  { reliance: ['illusions'] },
  puck:            { reliance: ['magic_burst'], vulnerable: ['hard_control'] },
  pudge:           { reliance: ['single_target_spell', 'channel'] },
  razor:           { reliance: ['right_click'] },
  sand_king:       { reliance: ['magic_burst', 'channel'] },
  storm_spirit:    { reliance: ['magic_burst'], vulnerable: ['silence', 'hard_control'] },
  sven:            { reliance: ['right_click'] },
  tiny:            { reliance: ['magic_burst', 'right_click'] },
  vengefulspirit:  { reliance: ['right_click'] },
  windrunner:      { reliance: ['right_click', 'evasion'] },
  zuus:            { reliance: ['magic_burst'] },
  kunkka:          { reliance: ['right_click', 'magic_burst'] },
  lina:            { reliance: ['magic_burst'] },
  lion:            { reliance: ['magic_burst', 'single_target_spell'] },
  shadow_shaman:   { reliance: ['single_target_spell', 'channel'] },
  slardar:         { reliance: ['right_click'] },
  tidehunter:      { reliance: ['passive'] },
  witch_doctor:    { reliance: ['channel', 'magic_burst'] },
  lich:            { reliance: ['magic_burst'] },
  riki:            { reliance: ['invisibility'] },
  enigma:          { reliance: ['channel', 'illusions'], vulnerable: ['hard_control', 'silence'] },
  tinker:          { reliance: ['magic_burst'], vulnerable: ['hard_control', 'silence'] },
  sniper:          { reliance: ['right_click'] },
  necrolyte:       { reliance: ['regen', 'magic_burst'] },
  warlock:         { reliance: ['illusions'] },
  beastmaster:     { reliance: ['illusions', 'right_click'] },
  queenofpain:     { reliance: ['magic_burst'], vulnerable: ['silence', 'hard_control'] },
  venomancer:      { reliance: ['illusions', 'magic_burst'] },
  faceless_void:   { reliance: ['right_click'] },
  skeleton_king:   { reliance: ['right_click', 'regen'] },
  death_prophet:   { reliance: ['magic_burst'] },
  phantom_assassin:{ reliance: ['evasion', 'right_click', 'passive'] },
  pugna:           { reliance: ['magic_burst'] },
  templar_assassin:{ reliance: ['right_click'] },
  viper:           { reliance: ['right_click', 'magic_burst'] },
  luna:            { reliance: ['right_click'] },
  dragon_knight:   { reliance: ['right_click', 'passive'] },
  dazzle:          { reliance: ['regen'] },
  rattletrap:      { reliance: ['single_target_spell', 'magic_burst'] },
  leshrac:         { reliance: ['magic_burst'] },
  furion:          { reliance: ['illusions', 'right_click'] },
  life_stealer:    { reliance: ['right_click', 'regen'] },
  dark_seer:       { reliance: ['illusions', 'magic_burst'] },
  clinkz:          { reliance: ['invisibility', 'right_click', 'illusions'] },
  omniknight:      { reliance: ['regen'] },
  enchantress:     { reliance: ['right_click'] },
  huskar:          { reliance: ['regen', 'right_click'] },
  night_stalker:   { reliance: ['right_click'] },
  broodmother:     { reliance: ['illusions', 'right_click'] },
  bounty_hunter:   { reliance: ['invisibility'] },
  weaver:          { reliance: ['invisibility', 'right_click'] },
  jakiro:          { reliance: ['magic_burst'] },
  batrider:        { reliance: ['single_target_spell', 'magic_burst'] },
  chen:            { reliance: ['illusions', 'regen'] },
  spectre:         { reliance: ['right_click', 'passive'] },
  ancient_apparition: { reliance: ['magic_burst'] },
  doom_bringer:    { reliance: ['single_target_spell'] },
  ursa:            { reliance: ['right_click', 'passive'] },
  spirit_breaker:  { reliance: ['single_target_spell'], vulnerable: ['interrupt'] },
  gyrocopter:      { reliance: ['right_click'] },
  alchemist:       { reliance: ['right_click', 'regen'] },
  invoker:         { reliance: ['magic_burst'] },
  silencer:        { reliance: ['magic_burst'] },
  obsidian_destroyer: { reliance: ['magic_burst', 'right_click'] },
  lycan:           { reliance: ['illusions', 'right_click'] },
  brewmaster:      { reliance: ['evasion', 'illusions', 'right_click'] },
  shadow_demon:    { reliance: ['single_target_spell', 'illusions', 'magic_burst'] },
  lone_druid:      { reliance: ['illusions', 'right_click'] },
  chaos_knight:    { reliance: ['illusions', 'right_click'] },
  meepo:           { reliance: ['illusions', 'right_click'], vulnerable: ['hard_control'] },
  treant:          { reliance: ['regen', 'invisibility'] },
  ogre_magi:       { reliance: ['magic_burst'] },
  undying:         { reliance: ['regen', 'illusions'] },
  rubick:          { reliance: ['magic_burst', 'single_target_spell'] },
  disruptor:       { reliance: ['magic_burst'] },
  nyx_assassin:    { reliance: ['invisibility', 'magic_burst'] },
  naga_siren:      { reliance: ['illusions', 'right_click'] },
  keeper_of_the_light: { reliance: ['magic_burst'] },
  wisp:            { reliance: ['regen'] },
  visage:          { reliance: ['illusions'] },
  slark:           { reliance: ['right_click', 'invisibility'] },
  medusa:          { reliance: ['right_click'] },
  troll_warlord:   { reliance: ['right_click'] },
  centaur:         { reliance: ['passive', 'right_click'] },
  magnataur:       { reliance: ['magic_burst'] },
  shredder:        { reliance: ['regen', 'passive', 'magic_burst'] },
  bristleback:     { reliance: ['passive', 'regen'] },
  tusk:            { reliance: ['single_target_spell'] },
  skywrath_mage:   { reliance: ['magic_burst', 'single_target_spell'] },
  abaddon:         { reliance: ['regen', 'right_click'] },
  elder_titan:     { reliance: ['right_click', 'magic_burst'] },
  legion_commander:{ reliance: ['single_target_spell', 'right_click'] },
  techies:         { reliance: ['magic_burst'], vulnerable: ['detection'] },
  ember_spirit:    { reliance: ['right_click', 'magic_burst'], vulnerable: ['hard_control', 'silence'] },
  earth_spirit:    { reliance: ['magic_burst'], vulnerable: ['hard_control', 'silence'] },
  abyssal_underlord: { reliance: ['magic_burst'] },
  terrorblade:     { reliance: ['illusions', 'right_click'] },
  phoenix:         { reliance: ['magic_burst', 'regen'] },
  oracle:          { reliance: ['regen'] },
  winter_wyvern:   { reliance: ['regen', 'magic_burst'] },
  arc_warden:      { reliance: ['illusions', 'right_click'], vulnerable: ['hard_control'] },
  monkey_king:     { reliance: ['right_click', 'passive'] },
  dark_willow:     { reliance: ['magic_burst'] },
  pangolier:       { reliance: ['right_click', 'magic_burst'], vulnerable: ['hard_control'] },
  grimstroke:      { reliance: ['magic_burst', 'single_target_spell'] },
  hoodwink:        { reliance: ['magic_burst', 'evasion'] },
  void_spirit:     { reliance: ['magic_burst'], vulnerable: ['hard_control', 'silence'] },
  snapfire:        { reliance: ['magic_burst'] },
  mars:            { reliance: ['right_click', 'passive'] },
  ringmaster:      { reliance: ['magic_burst'] },
  dawnbreaker:     { reliance: ['right_click', 'regen'] },
  marci:           { reliance: ['right_click'] },
  primal_beast:    { reliance: ['right_click', 'magic_burst'] },
  muerta:          { reliance: ['right_click', 'magic_burst'] },
  kez:             { reliance: ['right_click'] },
};

export function getHeroMechanics(shortName: string): HeroMechProfile {
  return HERO_MECHANICS[shortName] ?? {};
}
