import type { Hero } from './types';

export const HEROES: Hero[] = [
  {
    id: 1, name: 'antimage', displayName: 'Anti-Mage',
    attribute: 'agility', attack: 'melee', complexity: 2,
    roles: ['carry'], preferredRoles: ['carry'],
    strengths: ['Exceptional mana burn', 'High mobility with Blink', 'Hard to catch', 'Snowballs vs magic-heavy lineups'],
    weaknesses: ['Weak early game', 'Falls behind without farm', 'Weak vs physical damage'],
    powerSpikes: ['Level 6 (Mana Void)', 'BF + Manta', 'Level 25'],
    utilityTags: ['mobility', 'scaling'],
    needs: ['farm protection', 'early game support', 'space creation'],
  },
  {
    id: 2, name: 'axe', displayName: 'Axe',
    attribute: 'strength', attack: 'melee', complexity: 1,
    roles: ['offlane'], preferredRoles: ['offlane'],
    strengths: ['Strong lane presence', 'Reliable kill potential', 'Hard to kite in melee', 'Good vs illusions'],
    weaknesses: ['Slow', 'No ranged harass', 'Falls off late game'],
    powerSpikes: ['Level 6 (Culling Blade)', 'Blink Dagger', 'Blade Mail'],
    utilityTags: ['initiation', 'lockdown', 'lane_pressure'],
    needs: ['follow-up damage', 'ranged support', 'late-game carries'],
  },
  {
    id: 3, name: 'bane', displayName: 'Bane',
    attribute: 'intelligence', attack: 'ranged', complexity: 2,
    roles: ['support', 'hard_support'], preferredRoles: ['hard_support'],
    strengths: ['Strong disables', 'Reliable Nightmare', 'Fiend\'s Grip lockdown', 'Good vs illusions'],
    weaknesses: ['No burst damage', 'Squishy', 'Falls off without items'],
    powerSpikes: ['Level 6 (Fiend\'s Grip)', 'Aether Lens', 'Aghanim\'s Scepter'],
    utilityTags: ['lockdown', 'silence', 'stun'],
    needs: ['physical damage dealers', 'heroes to follow up on disables'],
  },
  {
    id: 4, name: 'bloodseeker', displayName: 'Bloodseeker',
    attribute: 'agility', attack: 'melee', complexity: 1,
    roles: ['carry', 'mid', 'offlane'], preferredRoles: ['carry', 'offlane'],
    strengths: ['Strong ganking potential', 'Vision on low-HP enemies', 'Good lane harass', 'Scales with kills'],
    weaknesses: ['Falls off very late', 'Countered by BKB', 'Position-dependent'],
    powerSpikes: ['Level 6 (Rupture)', 'Blade Mail', 'Level 12'],
    utilityTags: ['lane_pressure', 'burst', 'vision'],
    needs: ['reliable stuns', 'team fight follow-up'],
  },
  {
    id: 5, name: 'crystal_maiden', displayName: 'Crystal Maiden',
    attribute: 'intelligence', attack: 'ranged', complexity: 1,
    roles: ['support', 'hard_support'], preferredRoles: ['hard_support'],
    strengths: ['Global mana aura', 'Strong lane harass', 'Reliable Frostbite', 'High teamfight damage'],
    weaknesses: ['Very slow', 'Squishy', 'Easy to kill in teamfights'],
    powerSpikes: ['Level 6 (Freezing Field)', 'Aether Lens', 'Blink Dagger'],
    utilityTags: ['stun', 'aura_carrier', 'wave_clear', 'lockdown'],
    needs: ['peel', 'BKB cover', 'positioning support'],
  },
  {
    id: 6, name: 'drow_ranger', displayName: 'Drow Ranger',
    attribute: 'agility', attack: 'ranged', complexity: 1,
    roles: ['carry'], preferredRoles: ['carry'],
    strengths: ['High single-target damage', 'Global aura for ranged team', 'Good lane harass', 'Scales well'],
    weaknesses: ['No mobility', 'Countered by gap-closers', 'Weak vs melee initiators'],
    powerSpikes: ['Level 6 (Marksmanship)', 'Dragon Lance', 'Aghanim\'s Scepter'],
    utilityTags: ['lane_pressure', 'aura_carrier', 'scaling'],
    needs: ['front-line', 'space makers', 'ranged team composition'],
  },
  {
    id: 7, name: 'earthshaker', displayName: 'Earthshaker',
    attribute: 'strength', attack: 'melee', complexity: 2,
    roles: ['support', 'offlane'], preferredRoles: ['support'],
    strengths: ['Massive AoE teamfight', 'Reliable stun', 'Great with illusion lineups', 'Strong ganker'],
    weaknesses: ['Blink-dependent', 'Hard to play', 'Minimal damage without items'],
    powerSpikes: ['Blink Dagger', 'Level 6 (Echo Slam)', 'Aghanim\'s Scepter'],
    utilityTags: ['stun', 'initiation', 'lockdown', 'wave_clear'],
    needs: ['high-damage follows', 'ranged support', 'illusion or summon enemies to combo'],
  },
  {
    id: 8, name: 'juggernaut', displayName: 'Juggernaut',
    attribute: 'agility', attack: 'melee', complexity: 2,
    roles: ['carry'], preferredRoles: ['carry'],
    strengths: ['Blade Fury magic immunity', 'Healing Ward sustain', 'Strong laner', 'Scales with items'],
    weaknesses: ['Short attack range', 'Falls off vs heavy disables without BKB', 'Predictable'],
    powerSpikes: ['Level 6 (Omnislash)', 'Battle Fury', 'Aghanim\'s Scepter'],
    utilityTags: ['burst', 'heal', 'mobility', 'scaling'],
    needs: ['lane support', 'front-line', 'peel'],
  },
  {
    id: 9, name: 'mirana', displayName: 'Mirana',
    attribute: 'agility', attack: 'ranged', complexity: 2,
    roles: ['support', 'mid', 'carry'], preferredRoles: ['support', 'mid'],
    strengths: ['Long-range stun', 'Global ultimate', 'Good escape', 'Versatile'],
    weaknesses: ['Skill-shot dependent', 'No reliable disable without arrow hit', 'Squishy'],
    powerSpikes: ['Level 6 (Moonlight Shadow)', 'Aghanim\'s Scepter', 'Level 12'],
    utilityTags: ['stun', 'mobility', 'save', 'vision'],
    needs: ['reliable follow-up', 'backup disable'],
  },
  {
    id: 10, name: 'morphling', displayName: 'Morphling',
    attribute: 'agility', attack: 'ranged', complexity: 3,
    roles: ['carry', 'mid'], preferredRoles: ['carry'],
    strengths: ['Extremely hard to kill', 'High burst damage', 'Adaptive attribute shift', 'Can copy enemy ultimates'],
    weaknesses: ['Weak early laning', 'Mechanically demanding', 'Mana-hungry'],
    powerSpikes: ['Level 6', 'Ethereal Blade', 'Full items'],
    utilityTags: ['burst', 'mobility', 'scaling'],
    needs: ['early protection', 'space creation', 'lane support'],
  },
  {
    id: 11, name: 'shadow_fiend', displayName: 'Shadow Fiend',
    attribute: 'agility', attack: 'ranged', complexity: 2,
    roles: ['mid'], preferredRoles: ['mid'],
    strengths: ['Massive burst damage', 'Strong mid-game spike', 'Presence of the Dark Lord aura', 'High lane dominance'],
    weaknesses: ['Falls off very late', 'Squishy', 'No reliable escape'],
    powerSpikes: ['Level 6 (Requiem)', 'Shadow Blade / Eul\'s', 'Level 16'],
    utilityTags: ['burst', 'aura_carrier', 'wave_clear', 'lane_pressure'],
    needs: ['peel', 'setup', 'early-game supports'],
  },
  {
    id: 12, name: 'phantom_lancer', displayName: 'Phantom Lancer',
    attribute: 'agility', attack: 'melee', complexity: 2,
    roles: ['carry'], preferredRoles: ['carry'],
    strengths: ['Overwhelms single-target teams', 'Hard to focus in teamfights', 'Scales massively', 'Splitpush threat'],
    weaknesses: ['Hard countered by AoE', 'Weak early game', 'Falls off vs magic damage'],
    powerSpikes: ['Diffusal Blade + Manta', 'Level 6', 'Full illusion build'],
    utilityTags: ['scaling', 'mobility'],
    needs: ['AoE protection', 'early support', 'time to farm'],
  },
  {
    id: 13, name: 'puck', displayName: 'Puck',
    attribute: 'intelligence', attack: 'ranged', complexity: 3,
    roles: ['mid', 'offlane'], preferredRoles: ['mid'],
    strengths: ['Strong initiation', 'High mobility', 'Silence and lockdown', 'Slippery and hard to kill'],
    weaknesses: ['Fragile', 'Falls off late if behind', 'Item-dependent'],
    powerSpikes: ['Blink Dagger', 'Level 6 (Dream Coil)', 'Aghanim\'s Scepter'],
    utilityTags: ['initiation', 'silence', 'lockdown', 'mobility'],
    needs: ['follow-up damage', 'BKB-piercing damage after lockdown'],
  },
  {
    id: 14, name: 'pudge', displayName: 'Pudge',
    attribute: 'strength', attack: 'melee', complexity: 2,
    roles: ['support', 'offlane'], preferredRoles: ['support'],
    strengths: ['High single-target kill threat', 'Dismember lockdown', 'Grows stronger with kills', 'Meat Hook skill shots'],
    weaknesses: ['Skill-shot reliant', 'Slow', 'Countered by mobile heroes'],
    powerSpikes: ['Level 6 (Dismember)', 'Aether Lens', 'Aghanim\'s Scepter'],
    utilityTags: ['lockdown', 'initiation', 'burst'],
    needs: ['follow-up damage', 'ranged setup', 'vision'],
  },
  {
    id: 15, name: 'razor', displayName: 'Razor',
    attribute: 'agility', attack: 'ranged', complexity: 1,
    roles: ['mid', 'carry', 'offlane'], preferredRoles: ['mid'],
    strengths: ['Strong laner', 'Steals damage from carries', 'Good vs right-click heroes', 'Self-sufficient'],
    weaknesses: ['No mobility', 'Falls off vs magic damage', 'Needs levels'],
    powerSpikes: ['Level 6', 'Blade Mail', 'Eye of Skadi'],
    utilityTags: ['lane_pressure', 'tower_damage', 'aura_carrier'],
    needs: ['save support', 'teamfight follow-up'],
  },
  {
    id: 16, name: 'sand_king', displayName: 'Sand King',
    attribute: 'strength', attack: 'melee', complexity: 2,
    roles: ['offlane', 'support'], preferredRoles: ['offlane'],
    strengths: ['Massive teamfight AoE', 'Strong ganker', 'Good lane presence', 'Burrow escape'],
    weaknesses: ['Blink-dependent for initiating', 'High skill floor', 'Channeled ultimate'],
    powerSpikes: ['Blink Dagger', 'Level 6 (Epicenter)', 'Aghanim\'s Scepter'],
    utilityTags: ['initiation', 'stun', 'wave_clear', 'lockdown'],
    needs: ['front-line', 'high-damage follow-up', 'BKB cover'],
  },
  {
    id: 17, name: 'storm_spirit', displayName: 'Storm Spirit',
    attribute: 'intelligence', attack: 'ranged', complexity: 3,
    roles: ['mid'], preferredRoles: ['mid'],
    strengths: ['Extremely mobile', 'Strong snowball potential', 'Hard to catch', 'Scales with mana'],
    weaknesses: ['Mana-hungry early', 'Falls off without farm', 'Countered by mana burn'],
    powerSpikes: ['Level 6 (Ball Lightning)', 'Bloodstone', 'Level 18+'],
    utilityTags: ['mobility', 'burst', 'lockdown', 'scaling'],
    needs: ['early lane support', 'room to snowball'],
  },
  {
    id: 18, name: 'sven', displayName: 'Sven',
    attribute: 'strength', attack: 'melee', complexity: 1,
    roles: ['carry', 'offlane'], preferredRoles: ['carry'],
    strengths: ['Massive teamfight damage with God\'s Strength', 'AoE stun', 'Tanky', 'Good with aura carriers'],
    weaknesses: ['No mobility', 'Slow attack speed normally', 'Easy to kite'],
    powerSpikes: ['Level 6 (God\'s Strength)', 'Echo Sabre', 'BKB + Daedalus'],
    utilityTags: ['stun', 'tower_damage', 'roshan', 'scaling', 'aura_carrier'],
    needs: ['aura carriers', 'setup from supports', 'blink-like initiation'],
  },
  {
    id: 19, name: 'tiny', displayName: 'Tiny',
    attribute: 'strength', attack: 'melee', complexity: 2,
    roles: ['mid', 'support', 'carry'], preferredRoles: ['mid', 'support'],
    strengths: ['Massive burst damage', 'High mobility (Aghs)', 'Strong ganks', 'Tower damage'],
    weaknesses: ['Falls off without items', 'Slow attack speed early', 'Squishy early'],
    powerSpikes: ['Level 3 (Toss + Avalanche combo)', 'Aghanim\'s Scepter', 'Level 6'],
    utilityTags: ['burst', 'stun', 'initiation', 'tower_damage', 'roshan'],
    needs: ['follow-up lockdown', 'damage items'],
  },
  {
    id: 20, name: 'vengeful_spirit', displayName: 'Vengeful Spirit',
    attribute: 'agility', attack: 'ranged', complexity: 1,
    roles: ['support', 'hard_support'], preferredRoles: ['support'],
    strengths: ['Reliable stun', 'Damage reduction aura', 'Swap utility', 'Good lane harass'],
    weaknesses: ['Squishy', 'Swap can misfire', 'No escape'],
    powerSpikes: ['Level 6 (Nether Swap)', 'Aether Lens', 'Aghanim\'s Scepter'],
    utilityTags: ['stun', 'aura_carrier', 'initiation', 'save'],
    needs: ['follow-up damage', 'tank front-line'],
  },
  {
    id: 21, name: 'windranger', displayName: 'Windranger',
    attribute: 'universal', attack: 'ranged', complexity: 2,
    roles: ['support', 'mid', 'offlane'], preferredRoles: ['support', 'mid'],
    strengths: ['High single-target damage', 'Shackle shot setup', 'Windrun escape', 'Versatile'],
    weaknesses: ['Somewhat item-dependent', 'Winrun is defensive only', 'Falls off vs AoE'],
    powerSpikes: ['Level 6 (Focus Fire)', 'Aghanim\'s Shard', 'Maelstrom'],
    utilityTags: ['stun', 'burst', 'mobility', 'lane_pressure'],
    needs: ['team follow-up', 'AoE support'],
  },
  {
    id: 22, name: 'zeus', displayName: 'Zeus',
    attribute: 'intelligence', attack: 'ranged', complexity: 1,
    roles: ['mid', 'support'], preferredRoles: ['mid'],
    strengths: ['Global ultimate', 'Constant true sight', 'Huge teamfight damage', 'Laning dominance'],
    weaknesses: ['No mobility', 'Squishy', 'Predictable patterns'],
    powerSpikes: ['Level 6 (Thundergod\'s Wrath)', 'Aghanim\'s Scepter', 'Octarine Core'],
    utilityTags: ['burst', 'vision', 'wave_clear', 'tower_damage'],
    needs: ['save support', 'front-line', 'initiation'],
  },
  {
    id: 23, name: 'kunkka', displayName: 'Kunkka',
    attribute: 'strength', attack: 'melee', complexity: 2,
    roles: ['mid', 'offlane', 'support'], preferredRoles: ['mid'],
    strengths: ['Massive AoE damage', 'Strong initiation', 'Good aura carrier', 'Teamfight power'],
    weaknesses: ['Skill-shot reliant', 'Needs farm', 'No escape'],
    powerSpikes: ['Level 6 (Ghostship)', 'Daedalus / BKB', 'Aghanim\'s Scepter'],
    utilityTags: ['stun', 'burst', 'initiation', 'wave_clear', 'aura_carrier'],
    needs: ['follow-up AoE', 'save support'],
  },
  {
    id: 26, name: 'lion', displayName: 'Lion',
    attribute: 'intelligence', attack: 'ranged', complexity: 1,
    roles: ['support', 'hard_support'], preferredRoles: ['hard_support'],
    strengths: ['Double disable', 'High burst damage', 'Reliable stun + hex', 'Mana drain'],
    weaknesses: ['Squishy', 'No mobility', 'Long cooldowns'],
    powerSpikes: ['Level 6 (Finger of Death)', 'Aether Lens', 'Aghanim\'s Scepter'],
    utilityTags: ['stun', 'lockdown', 'burst', 'silence'],
    needs: ['physical damage follow-up', 'front-line'],
  },
  {
    id: 30, name: 'witch_doctor', displayName: 'Witch Doctor',
    attribute: 'intelligence', attack: 'ranged', complexity: 1,
    roles: ['support', 'hard_support'], preferredRoles: ['support', 'hard_support'],
    strengths: ['Strong healer', 'Paralyzing Cask chain stun', 'Massive Death Ward damage', 'Voodoo Restoration'],
    weaknesses: ['Channeled ultimate', 'Squishy', 'Needs protection'],
    powerSpikes: ['Level 6 (Death Ward)', 'Aghanim\'s Scepter', 'Aghanim\'s Shard'],
    utilityTags: ['stun', 'heal', 'burst', 'lockdown'],
    needs: ['BKB cover', 'peel', 'initiation'],
  },
  {
    id: 68, name: 'ancient_apparition', displayName: 'Ancient Apparition',
    attribute: 'intelligence', attack: 'ranged', complexity: 2,
    roles: ['support', 'hard_support'], preferredRoles: ['hard_support'],
    strengths: ['Counters healing lineups', 'Global ultimate range', 'Good lane harass', 'Ice Blast prevents healing'],
    weaknesses: ['Skill-shot reliant', 'Low base damage', 'Squishy'],
    powerSpikes: ['Level 6 (Ice Blast)', 'Aether Lens', 'Aghanim\'s Scepter'],
    utilityTags: ['burst', 'lockdown', 'vision', 'wave_clear'],
    needs: ['physical damage dealers', 'initiation', 'front-line'],
  },
  {
    id: 74, name: 'invoker', displayName: 'Invoker',
    attribute: 'intelligence', attack: 'ranged', complexity: 3,
    roles: ['mid'], preferredRoles: ['mid'],
    strengths: ['Highest skill ceiling', 'Extremely versatile spell repertoire', 'Scales to late game', 'Adapt to any situation'],
    weaknesses: ['Requires high skill to pilot', 'Weak very early', 'Punished by disjoints'],
    powerSpikes: ['Level 6+', 'Aghanim\'s Scepter', 'Level 20+'],
    utilityTags: ['burst', 'wave_clear', 'stun', 'initiation', 'mobility', 'scaling'],
    needs: ['early support', 'understanding of spell combos'],
  },
  {
    id: 25, name: 'lina', displayName: 'Lina',
    attribute: 'intelligence', attack: 'ranged', complexity: 2,
    roles: ['mid', 'support'], preferredRoles: ['mid'],
    strengths: ['High burst damage', 'Reliable stun', 'Scales into carry', 'Good laner'],
    weaknesses: ['Squishy', 'Long cooldowns early', 'No mobility'],
    powerSpikes: ['Level 6 (Laguna Blade)', 'Aghanim\'s Scepter', 'Dragon Lance'],
    utilityTags: ['burst', 'stun', 'tower_damage', 'lane_pressure'],
    needs: ['peel', 'front-line', 'initiation'],
  },
  {
    id: 41, name: 'faceless_void', displayName: 'Faceless Void',
    attribute: 'agility', attack: 'melee', complexity: 2,
    roles: ['carry'], preferredRoles: ['carry'],
    strengths: ['Chronosphere teamfight control', 'High right-click DPS', 'Backtrack pseudo-evasion', 'Scaling carry'],
    weaknesses: ['Can trap allies in Chrono', 'Item-dependent', 'Weak without farm'],
    powerSpikes: ['Level 6 (Chronosphere)', 'Maelstrom / MKB', 'Full items'],
    utilityTags: ['lockdown', 'scaling', 'burst', 'roshan'],
    needs: ['setup supports', 'AoE follow-up inside Chrono', 'time to farm'],
  },
  {
    id: 29, name: 'tidehunter', displayName: 'Tidehunter',
    attribute: 'strength', attack: 'melee', complexity: 1,
    roles: ['offlane', 'support'], preferredRoles: ['offlane'],
    strengths: ['Ravage teamfight ultimate', 'Good lane presence', 'Natural tankiness', 'Reliable AoE disable'],
    weaknesses: ['Ravage countered by BKB', 'Slow', 'Limited damage late'],
    powerSpikes: ['Level 6 (Ravage)', 'Blink Dagger', 'Aghanim\'s Shard'],
    utilityTags: ['stun', 'initiation', 'wave_clear', 'lockdown', 'aura_carrier'],
    needs: ['high-damage cores', 'follow-up AoE'],
  },
  {
    id: 31, name: 'lich', displayName: 'Lich',
    attribute: 'intelligence', attack: 'ranged', complexity: 1,
    roles: ['hard_support'], preferredRoles: ['hard_support'],
    strengths: ['Strong laning with Sacrifice', 'Frost Shield protection', 'Chain Frost teamfight', 'Aura carrier'],
    weaknesses: ['Squishy', 'No escape', 'Chain Frost can miss'],
    powerSpikes: ['Level 6 (Chain Frost)', 'Aghanim\'s Scepter', 'Aghanim\'s Shard'],
    utilityTags: ['stun', 'aura_carrier', 'wave_clear', 'save'],
    needs: ['front-line', 'initiation', 'carries to protect'],
  },
  {
    id: 33, name: 'enigma', displayName: 'Enigma',
    attribute: 'universal', attack: 'ranged', complexity: 2,
    roles: ['offlane', 'support'], preferredRoles: ['offlane', 'support'],
    strengths: ['Black Hole game-winning teamfight', 'Creep summoning', 'Midnight Pulse damage', 'Strong jungler'],
    weaknesses: ['Channeled ultimate countered by BKB', 'Needs BKB from enemies to be useless', 'Item-dependent'],
    powerSpikes: ['Blink Dagger', 'Level 6 (Black Hole)', 'Aghanim\'s Scepter'],
    utilityTags: ['initiation', 'lockdown', 'wave_clear', 'roshan'],
    needs: ['high-damage follows', 'heroes that can use Eidolons'],
  },
  {
    id: 89, name: 'naga_siren', displayName: 'Naga Siren',
    attribute: 'agility', attack: 'melee', complexity: 2,
    roles: ['carry'], preferredRoles: ['carry'],
    strengths: ['Song of the Siren buyback prevention', 'Illusion army', 'Strong splitpush', 'Scales extremely well'],
    weaknesses: ['Weak laner', 'Needs farm', 'Countered by AoE'],
    powerSpikes: ['Diffusal Blade', 'Level 6 (Song)', 'Full item build'],
    utilityTags: ['scaling', 'lockdown', 'mobility'],
    needs: ['early support', 'AoE protection', 'time to farm'],
  },
  {
    id: 53, name: 'nature_prophet', displayName: 'Nature\'s Prophet',
    attribute: 'intelligence', attack: 'ranged', complexity: 2,
    roles: ['offlane', 'support', 'carry'], preferredRoles: ['offlane'],
    strengths: ['Global presence via Teleportation', 'Strong split push', 'Tower pressure', 'Summon treants'],
    weaknesses: ['Squishy', 'Predictable patterns', 'Weak in direct teamfights'],
    powerSpikes: ['Level 6 (Wrath of Nature)', 'Aghanim\'s Scepter', 'Dagger / Force Staff'],
    utilityTags: ['tower_damage', 'wave_clear', 'mobility', 'vision'],
    needs: ['teamfight follow-up', 'reliable stuns'],
  },
  {
    id: 57, name: 'omniknight', displayName: 'Omniknight',
    attribute: 'strength', attack: 'melee', complexity: 1,
    roles: ['support', 'hard_support'], preferredRoles: ['support'],
    strengths: ['Strong healer', 'Guardian Angel magic immunity', 'Good laner', 'Repel dispel'],
    weaknesses: ['No mobility', 'Guardian Angel countered by pure damage', 'Needs carry to protect'],
    powerSpikes: ['Level 6 (Guardian Angel)', 'Aghanim\'s Scepter', 'Aether Lens'],
    utilityTags: ['heal', 'save', 'dispel', 'aura_carrier'],
    needs: ['right-click carry to protect', 'frontline tank'],
  },
  {
    id: 97, name: 'magnus', displayName: 'Magnus',
    attribute: 'strength', attack: 'melee', complexity: 2,
    roles: ['offlane', 'support'], preferredRoles: ['offlane'],
    strengths: ['Reverse Polarity massive AoE stun', 'Empower damage buff for team', 'Skewer engage', 'Great with AoE ultimates'],
    weaknesses: ['Falls off solo', 'Relies on follow-up', 'Blink-dependent'],
    powerSpikes: ['Blink Dagger', 'Level 6 (Reverse Polarity)', 'Aghanim\'s Scepter'],
    utilityTags: ['stun', 'initiation', 'lockdown', 'aura_carrier'],
    needs: ['AoE damage follow-up', 'Chrono / Black Hole / Ravage combo'],
  },
  {
    id: 91, name: 'io', displayName: 'Io',
    attribute: 'universal', attack: 'ranged', complexity: 3,
    roles: ['hard_support'], preferredRoles: ['hard_support'],
    strengths: ['Global relocate', 'Strong heal with Overcharge', 'Tether movement speed', 'Saves allies globally'],
    weaknesses: ['Extremely item-dependent', 'Useless without a strong carry', 'Hard to play'],
    powerSpikes: ['Level 6 (Relocate)', 'Mek / Holy Locket', 'Aghanim\'s Scepter'],
    utilityTags: ['save', 'heal', 'mobility', 'roshan'],
    needs: ['high-impact carry partner', 'strong laning duo'],
  },
  {
    id: 94, name: 'medusa', displayName: 'Medusa',
    attribute: 'agility', attack: 'ranged', complexity: 2,
    roles: ['carry'], preferredRoles: ['carry'],
    strengths: ['Insanely tanky with Mana Shield', 'Stone Gaze in teamfights', 'Split Shot farming', 'Hyper-carry late game'],
    weaknesses: ['Very slow farmer early', 'Needs massive farm', 'Weak laner'],
    powerSpikes: ['Manta Style', 'Aghanim\'s Scepter', 'Full items (45+ min)'],
    utilityTags: ['scaling', 'lockdown', 'roshan'],
    needs: ['heavy support', 'time to farm', 'early game carries from team'],
  },
  {
    id: 86, name: 'rubick', displayName: 'Rubick',
    attribute: 'intelligence', attack: 'ranged', complexity: 3,
    roles: ['support'], preferredRoles: ['support'],
    strengths: ['Spell steal changes every fight', 'Telekinesis setup', 'Fade Bolt reduces damage', 'Versatile'],
    weaknesses: ['Squishy', 'Stolen spell requires enemy to have good ultimate', 'Skill-dependent'],
    powerSpikes: ['Level 6 (Spell Steal)', 'Aether Lens', 'Aghanim\'s Scepter'],
    utilityTags: ['stun', 'lockdown', 'initiation', 'burst', 'save'],
    needs: ['enemy lineup with strong stealable ultimates', 'follow-up'],
  },
];

export const getHeroById = (id: number): Hero | undefined =>
  HEROES.find(h => h.id === id);

export const getHeroByName = (name: string): Hero | undefined =>
  HEROES.find(h => h.name === name || h.displayName.toLowerCase() === name.toLowerCase());
